/**
 * Tags of the type inventory's pairings (@sb/spec INVENTORY_FONT_PAIRS), by pairing id: stance families, voice and the
 * trades a pairing suits (empty: any trade). One entry per pairing (packages/inventory/test/type-inventory.test.ts).
 */
import type { PairingTags } from "./type-inventory.ts";

export const PAIRING_TAGS: Record<string, PairingTags> = {
  "besley--work-sans--courier-prime": { stances: ["print"], voice: ["old", "loud"], trades: ["car-repair", "builder"] },
  "rokkitt--karla--courier-prime": { stances: ["print", "signage"], voice: ["old", "exact"], trades: ["car-repair", "builder"] },
  "chivo--ibm-plex-sans--ibm-plex-mono": { stances: ["print", "modernist"], voice: ["exact", "new"], trades: ["car-repair", "accountant", "builder"] },
  "schibsted-grotesk--source-serif-4": { stances: ["print", "contemporary"], voice: ["exact", "new"], trades: ["accountant", "physio", "dental"] },
  "chivo--source-serif-4": { stances: ["print"], voice: ["exact", "loud"], trades: ["accountant", "builder", "shop"] },
  "poltawski-nowy--schibsted-grotesk": { stances: ["print"], voice: ["old", "exact"], trades: ["accountant", "restaurant", "shop"] },
  "libre-caslon-text": { stances: ["print"], voice: ["old", "quiet"], trades: ["bakery", "restaurant", "shop"] },
  "literata--libre-franklin": { stances: ["print"], voice: ["quiet", "exact"], trades: ["accountant", "physio"] },
  "sofia-sans-condensed--atkinson-hyperlegible-next--red-hat-mono": { stances: ["print", "modernist"], voice: ["exact", "quiet"], trades: ["dental", "physio"] },
  "young-serif--alegreya": { stances: ["print", "craft", "nature"], voice: ["warm", "old"], trades: ["bakery", "tourist-farm", "shop"] },
  "vollkorn--work-sans": { stances: ["print", "craft"], voice: ["warm", "old"], trades: ["bakery", "restaurant"] },
  "schibsted-grotesk--sometype-mono": { stances: ["print"], voice: ["exact", "loud"], trades: ["car-repair", "builder", "shop"] },
  "overpass--albert-sans--red-hat-mono": { stances: ["print", "signage"], voice: ["exact", "new"], trades: ["physio", "tourist-farm"] },
  "besley--literata": { stances: ["print"], voice: ["old", "loud"], trades: ["restaurant", "bakery"] },
  "work-sans--literata--ibm-plex-mono": { stances: ["print", "contemporary"], voice: ["exact", "quiet"], trades: ["accountant"] },
  "crimson-pro--work-sans": { stances: ["print"], voice: ["quiet", "old"], trades: ["accountant", "shop"] },
  "big-shoulders--atkinson-hyperlegible-next": { stances: ["signage"], voice: ["loud", "new"], trades: ["car-repair", "builder"] },
  "big-shoulders--public-sans": { stances: ["signage"], voice: ["loud", "exact"], trades: ["car-repair", "builder", "shop"] },
  "big-shoulders--literata": { stances: ["signage", "contemporary"], voice: ["loud"], trades: ["restaurant", "shop"] },
  "oswald--source-sans-3": { stances: ["signage"], voice: ["loud", "exact"], trades: ["car-repair", "builder", "shop"] },
  "oswald--crimson-pro": { stances: ["signage", "print"], voice: ["loud", "old"], trades: ["restaurant", "bakery"] },
  "overpass": { stances: ["signage", "nature"], voice: ["exact"], trades: ["tourist-farm", "physio"] },
  "signika": { stances: ["signage", "nature"], voice: ["exact", "quiet"], trades: ["tourist-farm", "physio", "dental"] },
  "krona-one--work-sans": { stances: ["signage", "contemporary"], voice: ["loud", "new"], trades: ["hairdresser", "shop", "car-repair"] },
  "krona-one--karla": { stances: ["signage", "modernist"], voice: ["loud", "new"], trades: ["shop", "hairdresser"] },
  "league-spartan--libre-franklin": { stances: ["signage", "modernist"], voice: ["loud"], trades: ["builder", "shop"] },
  "rokkitt--signika": { stances: ["signage"], voice: ["old", "exact"], trades: ["builder", "tourist-farm"] },
  "big-shoulders-stencil--ibm-plex-sans--ibm-plex-mono": { stances: ["signage", "craft"], voice: ["loud", "exact"], trades: ["builder", "car-repair"] },
  "big-shoulders-stencil--work-sans": { stances: ["signage", "craft"], voice: ["loud"], trades: ["builder", "car-repair"] },
  "sofia-sans-condensed--public-sans": { stances: ["signage", "modernist"], voice: ["exact"], trades: ["builder", "accountant"] },
  "besley--public-sans": { stances: ["signage", "print"], voice: ["old", "loud"], trades: ["builder", "car-repair", "shop"] },
  "chivo--atkinson-hyperlegible-next--red-hat-mono": { stances: ["signage"], voice: ["exact", "loud"], trades: ["car-repair"] },
  "young-serif--work-sans": { stances: ["craft", "print"], voice: ["warm", "loud"], trades: ["bakery", "restaurant"] },
  "young-serif--dm-sans": { stances: ["craft"], voice: ["warm"], trades: ["bakery", "shop", "hairdresser"] },
  "aleo--karla": { stances: ["craft", "nature"], voice: ["warm"], trades: ["bakery", "tourist-farm"] },
  "aleo--nunito-sans": { stances: ["craft"], voice: ["warm", "quiet"], trades: ["bakery", "physio"] },
  "aleo": { stances: ["craft"], voice: ["warm"], trades: ["bakery", "tourist-farm", "restaurant"] },
  "aleo--signika": { stances: ["craft", "nature"], voice: ["warm", "exact"], trades: ["tourist-farm"] },
  "vollkorn": { stances: ["craft", "print"], voice: ["warm", "old"], trades: ["bakery", "restaurant"] },
  "vollkorn--karla": { stances: ["craft"], voice: ["warm", "old"], trades: ["bakery", "shop"] },
  "alegreya--albert-sans": { stances: ["craft", "nature"], voice: ["warm"], trades: ["tourist-farm", "shop"] },
  "alegreya": { stances: ["craft", "nature"], voice: ["warm", "old"], trades: ["restaurant", "tourist-farm"] },
  "poltawski-nowy--atkinson-hyperlegible-next": { stances: ["craft", "print"], voice: ["old", "warm"], trades: ["bakery", "shop"] },
  "fraunces--atkinson-hyperlegible-next": { stances: ["craft"], voice: ["warm", "new"], trades: ["bakery", "physio"] },
  "fraunces--work-sans": { stances: ["craft", "contemporary"], voice: ["warm", "loud"], trades: ["restaurant", "shop"] },
  "fraunces--albert-sans": { stances: ["craft", "nature"], voice: ["warm"], trades: ["tourist-farm"] },
  "big-shoulders-stencil--karla": { stances: ["craft"], voice: ["loud", "warm"], trades: ["shop", "builder"] },
  "bitter--atkinson-hyperlegible-next": { stances: ["craft", "print"], voice: ["exact", "warm"], trades: ["builder", "physio"] },
  "jost": { stances: ["modernist"], voice: ["exact", "new"], trades: ["accountant", "dental", "physio"] },
  "jost--literata": { stances: ["modernist"], voice: ["exact", "quiet"], trades: ["accountant", "dental"] },
  "jost--newsreader": { stances: ["modernist", "print"], voice: ["quiet"], trades: ["hairdresser", "dental"] },
  "league-spartan--source-serif-4": { stances: ["modernist"], voice: ["loud", "exact"], trades: ["accountant", "builder"] },
  "archivo--source-serif-4": { stances: ["modernist", "print"], voice: ["exact"], trades: ["accountant", "physio"] },
  "archivo--literata": { stances: ["modernist"], voice: ["exact", "quiet"], trades: ["accountant", "dental"] },
  "sofia-sans-condensed--instrument-sans": { stances: ["modernist"], voice: ["exact", "new"], trades: ["dental", "accountant"] },
  "krona-one--source-sans-3": { stances: ["modernist"], voice: ["new", "exact"], trades: ["dental", "car-repair"] },
  "brygada-1918": { stances: ["modernist", "print"], voice: ["old", "quiet"], trades: ["accountant", "restaurant"] },
  "brygada-1918--albert-sans": { stances: ["modernist"], voice: ["old", "exact"], trades: ["accountant", "physio"] },
  "brygada-1918--libre-franklin": { stances: ["modernist", "print"], voice: ["old", "exact"], trades: ["accountant", "shop"] },
  "albert-sans--source-serif-4": { stances: ["modernist"], voice: ["exact", "quiet"], trades: ["accountant", "physio"] },
  "epilogue--source-serif-4": { stances: ["modernist", "contemporary"], voice: ["loud", "exact"], trades: ["accountant", "builder"] },
  "cormorant--albert-sans": { stances: ["nature"], voice: ["quiet", "old"], trades: ["restaurant", "tourist-farm"] },
  "cormorant--karla": { stances: ["nature", "craft"], voice: ["quiet", "warm"], trades: ["tourist-farm", "hairdresser"] },
  "cormorant--atkinson-hyperlegible-next": { stances: ["nature", "contemporary"], voice: ["quiet", "new"], trades: ["hairdresser", "physio"] },
  "alegreya--signika": { stances: ["nature"], voice: ["warm", "exact"], trades: ["tourist-farm"] },
  "yrsa--atkinson-hyperlegible-next": { stances: ["nature", "print"], voice: ["quiet"], trades: ["physio", "tourist-farm"] },
  "yrsa--work-sans": { stances: ["nature", "print"], voice: ["quiet", "old"], trades: ["restaurant", "shop"] },
  "besley--albert-sans": { stances: ["nature", "signage"], voice: ["old", "loud"], trades: ["tourist-farm", "builder"] },
  "rokkitt--albert-sans": { stances: ["nature", "signage"], voice: ["exact"], trades: ["tourist-farm", "builder"] },
  "crimson-pro": { stances: ["nature", "print"], voice: ["quiet", "old"], trades: ["restaurant", "tourist-farm"] },
  "lora--albert-sans": { stances: ["nature"], voice: ["warm", "quiet"], trades: ["physio", "tourist-farm"] },
  "eb-garamond--albert-sans": { stances: ["nature"], voice: ["quiet", "old"], trades: ["restaurant", "tourist-farm"] },
  "unbounded--instrument-sans": { stances: ["contemporary"], voice: ["loud", "new"], trades: ["hairdresser", "shop", "car-repair"] },
  "unbounded--work-sans": { stances: ["contemporary"], voice: ["loud", "new"], trades: ["car-repair", "shop"] },
  "syne--instrument-sans": { stances: ["contemporary"], voice: ["new"], trades: ["hairdresser", "shop"] },
  "syne--literata": { stances: ["contemporary", "print"], voice: ["new", "quiet"], trades: ["hairdresser", "restaurant"] },
  "bodoni-moda--work-sans": { stances: ["contemporary", "print"], voice: ["new", "loud"], trades: ["hairdresser", "shop"] },
  "bodoni-moda--instrument-sans": { stances: ["contemporary"], voice: ["new", "quiet"], trades: ["hairdresser", "dental"] },
  "bodoni-moda--literata": { stances: ["contemporary", "print"], voice: ["quiet", "old"], trades: ["restaurant"] },
  "dm-serif-display--instrument-sans": { stances: ["contemporary"], voice: ["new"], trades: ["hairdresser", "dental"] },
  "dm-serif-display--atkinson-hyperlegible-next": { stances: ["contemporary"], voice: ["new", "quiet"], trades: ["dental", "physio"] },
  "epilogue--literata": { stances: ["contemporary"], voice: ["loud"], trades: ["shop", "restaurant"] },
  "epilogue": { stances: ["contemporary"], voice: ["loud", "new"], trades: ["car-repair", "builder"] },
  "chivo": { stances: ["contemporary"], voice: ["loud"], trades: ["car-repair", "shop"] },
  "atkinson-hyperlegible-next": { stances: ["contemporary"], voice: ["exact", "quiet"], trades: ["physio", "dental"] },
  "instrument-sans--source-serif-4": { stances: ["contemporary"], voice: ["exact", "quiet"], trades: ["dental", "accountant"] },
  "newsreader--instrument-sans": { stances: ["contemporary", "print"], voice: ["quiet"], trades: ["dental", "hairdresser"] },
  "bricolage-grotesque--literata": { stances: ["contemporary"], voice: ["warm", "new"], trades: ["restaurant", "shop"] },
};
