/**
 * Curated palettes (design-studio.md §4.1, inventory I2): drawn from real-world sources of colour character (enamel
 * signs, Slovene folk paint, alpine and Karst landscape, print inks, workwear), one line each in `source`. Every role
 * is stored as a site renders it: each text and background pair passes as stored (paletteIssues in checks.ts, held in
 * packages/inventory/test), so nothing relies on render-time repair. Registered as drafts; the owner approves them in
 * the gallery.
 */
import type { Colors } from "@sb/spec";
import type { Ground } from "../schema.ts";

export interface CuratedPalette {
  /** The asset name: registered as palette/<id>. */
  id: string;
  /** Where the colours come from, in one line. */
  source: string;
  ground: Ground;
  /** Read from the primary (or band) hue (temperatureOf). */
  temperature: "warm" | "cool" | "neutral";
  /** Stance ids (spec studio/stances.ts) and stance families (print, signage, craft, modernist, place, nature, contemporary). */
  stances: string[];
  /** Business types and sub-trades it suits. */
  trades: string[];
  /** Temperature, the stance deck's palette words (signal, earth, deep, muted, bright, two-colour, monochrome, neutral) and band. */
  mood: string[];
  colors: Colors;
}

export const CURATED_PALETTES: readonly CuratedPalette[] = [
  {
    id: "docket-carbon",
    source: "Workshop job ticket: carbon-copy blue on white, a red rubber stamp.",
    ground: "white",
    temperature: "cool",
    stances: ["workshop-docket", "print"],
    trades: ["builder", "car-repair"],
    mood: ["band", "cool", "signal", "two-colour"],
    colors: { background: "#ffffff", surface: "#edf1f8", text: "#172036", muted: "#5f6574", primary: "#2a4a9a", onPrimary: "#ffffff", accent: "#d9483b", border: "#dce0e8", inverse: "#172654", onInverse: "#eef0f6", band: "#c63a30", onBand: "#eef0f6" },
  },
  {
    id: "docket-pink-copy",
    source: "The pink copy of a triplicate form, filled in with a blue ballpoint.",
    ground: "tint",
    temperature: "cool",
    stances: ["workshop-docket", "print"],
    trades: ["accountant", "builder", "car-repair"],
    mood: ["band", "cool", "two-colour"],
    colors: { background: "#f8e4ea", surface: "#fbeff3", text: "#271a22", muted: "#6c5d64", primary: "#24438f", onPrimary: "#ffffff", accent: "#c43d5a", border: "#d5c9cd", inverse: "#1b1f33", onInverse: "#eef0f6", band: "#24438f", onBand: "#eef0f6" },
  },
  {
    id: "seed-packet-poppy",
    source: "Litho seed packet: poppy red and leaf green on white, a marigold strip.",
    ground: "white",
    temperature: "warm",
    stances: ["seed-packet", "print"],
    trades: ["shop/deli", "shop/florist", "tourist-farm"],
    mood: ["band", "bright", "earth", "warm"],
    colors: { background: "#ffffff", surface: "#eef4ea", text: "#2a1c16", muted: "#6e6561", primary: "#b8322a", onPrimary: "#ffffff", accent: "#3f7d3a", border: "#dee3d9", inverse: "#261a14", onInverse: "#f6f1ee", band: "#e8b730", onBand: "#2a1c16" },
  },
  {
    id: "seed-packet-bean",
    source: "Bean seed packet: pale pod-green paper, pod-green ink, ochre type.",
    ground: "tint",
    temperature: "cool",
    stances: ["seed-packet", "print", "nature"],
    trades: ["bakery", "shop/deli", "tourist-farm"],
    mood: ["band", "cool", "earth"],
    colors: { background: "#e8f2dc", surface: "#f1f7ea", text: "#1f2a18", muted: "#5d6855", primary: "#4a7428", onPrimary: "#ffffff", accent: "#a8631a", border: "#cdd4c6", inverse: "#1f2a18", onInverse: "#f0f5ed", band: "#f0c64a", onBand: "#1f2a18" },
  },
  {
    id: "pharmacy-amber",
    source: "Old pharmacy label: a green cross on white, amber bottle glass.",
    ground: "white",
    temperature: "cool",
    stances: ["print"],
    trades: ["dental", "physio", "shop"],
    mood: ["band", "cool", "two-colour"],
    colors: { background: "#ffffff", surface: "#ebf4ef", text: "#10241d", muted: "#5c6a65", primary: "#0c6b48", onPrimary: "#ffffff", accent: "#c27410", border: "#d9e3de", inverse: "#10261e", onInverse: "#ecf5f2", band: "#f2d49a", onBand: "#10241d" },
  },
  {
    id: "broadsheet",
    source: "Daily broadsheet: newsprint black and one masthead red.",
    ground: "white",
    temperature: "warm",
    stances: ["editorial-magazine", "print"],
    trades: ["accountant", "hairdresser", "restaurant"],
    mood: ["band", "monochrome", "signal", "warm"],
    colors: { background: "#ffffff", surface: "#f0f0f1", text: "#1a1a1c", muted: "#666667", primary: "#1a1a1c", onPrimary: "#ffffff", accent: "#d0342c", border: "#e1e1e2", inverse: "#1a1a1c", onInverse: "#f2f2f3", band: "#c0302a", onBand: "#f2f2f3" },
  },
  {
    id: "postcard-adriatic",
    source: "1960s Adriatic tourist postcard: sea blue, sun yellow, coral.",
    ground: "white",
    temperature: "cool",
    stances: ["print", "place"],
    trades: ["restaurant", "tourist-farm"],
    mood: ["band", "bright", "cool"],
    colors: { background: "#ffffff", surface: "#e6f0f8", text: "#14243a", muted: "#5b6675", primary: "#1f6aa8", onPrimary: "#ffffff", accent: "#e0533d", border: "#d7e2eb", inverse: "#0f3352", onInverse: "#eef3f6", band: "#f5c542", onBand: "#14243a" },
  },
  {
    id: "recipe-card",
    source: "Recipe written on a pink index card, a sage pencil line.",
    ground: "tint",
    temperature: "warm",
    stances: ["print"],
    trades: ["bakery", "restaurant"],
    mood: ["band", "muted", "two-colour", "warm"],
    colors: { background: "#fbe9e5", surface: "#fdf3f0", text: "#2d1b1b", muted: "#715f5e", primary: "#9e2f3a", onPrimary: "#ffffff", accent: "#3f7a64", border: "#dacecc", inverse: "#2d1b1b", onInverse: "#f5efef", band: "#3e7863", onBand: "#f5efef" },
  },
  {
    id: "riso-pink-blue",
    source: "Risograph print: fluorescent pink over medium blue.",
    ground: "white",
    temperature: "cool",
    stances: ["print", "contemporary", "colour-block"],
    trades: ["hairdresser", "shop/boutique", "shop/florist"],
    mood: ["band", "bright", "cool", "two-colour"],
    colors: { background: "#ffffff", surface: "#eef3fb", text: "#1c1f2b", muted: "#65676f", primary: "#0060a8", onPrimary: "#ffffff", accent: "#e8508f", border: "#dde2ea", inverse: "#1c1f2b", onInverse: "#f0f1f5", band: "#ff8fc0", onBand: "#1c1f2b" },
  },
  {
    id: "enamel-cobalt",
    source: "Enamel street plate: cobalt with a white rim, an orange house number.",
    ground: "white",
    temperature: "cool",
    stances: ["signage"],
    trades: ["accountant", "builder", "car-repair"],
    mood: ["band", "cool", "signal", "two-colour"],
    colors: { background: "#ffffff", surface: "#e9eef8", text: "#121c2e", muted: "#5e6571", primary: "#1d4fa0", onPrimary: "#ffffff", accent: "#d65a2a", border: "#dce1ec", inverse: "#101a2c", onInverse: "#eef1f6", band: "#1d4fa0", onBand: "#eef1f6" },
  },
  {
    id: "trail-granite",
    source: "Mountain trail mark painted on granite: a red ring on grey stone.",
    ground: "tint",
    temperature: "warm",
    stances: ["trail-marker", "signage", "nature"],
    trades: ["builder", "physio", "tourist-farm"],
    mood: ["band", "earth", "signal", "warm"],
    colors: { background: "#e6edf2", surface: "#f0f4f7", text: "#1e2429", muted: "#5e6469", primary: "#b8141b", onPrimary: "#ffffff", accent: "#d84a2c", border: "#ccd1d4", inverse: "#1e2429", onInverse: "#f0f2f4", band: "#3f4a52", onBand: "#f0f2f4" },
  },
  {
    id: "shopfront-gilt",
    source: "Old shop fascia: a bottle-green board with gilded letters.",
    ground: "dark",
    temperature: "warm",
    stances: ["signage", "craft"],
    trades: ["bakery", "restaurant", "shop/boutique", "shop/deli"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#0f2a20", surface: "#143327", text: "#edf1ea", muted: "#94a199", primary: "#d4a84a", onPrimary: "#0f2a20", accent: "#d4a84a", border: "#213e33", inverse: "#1b3f30", onInverse: "#ecf5f2", band: "#d4a84a", onBand: "#0f2a20" },
  },
  {
    id: "detour-orange",
    source: "Roadworks detour sign: safety orange on asphalt.",
    ground: "dark",
    temperature: "warm",
    stances: ["signage"],
    trades: ["builder", "car-repair"],
    mood: ["band", "signal", "warm"],
    colors: { background: "#17191c", surface: "#1f2226", text: "#eef0f2", muted: "#8f9194", primary: "#f0592a", onPrimary: "#17191c", accent: "#f0592a", border: "#2d3034", inverse: "#262a2f", onInverse: "#f1f2f4", band: "#f0592a", onBand: "#17191c" },
  },
  {
    id: "hazard-yellow",
    source: "Site hazard signage: black on signal yellow.",
    ground: "tint",
    temperature: "warm",
    stances: ["signage", "colour-block"],
    trades: ["builder", "car-repair"],
    mood: ["bright", "signal", "warm"],
    colors: { background: "#f7d64a", surface: "#fae48a", text: "#1c1a14", muted: "#625625", primary: "#1c1a14", onPrimary: "#ffffff", accent: "#d8352a", border: "#cebc72", inverse: "#1c1a14", onInverse: "#f4f3f0" },
  },
  {
    id: "cafe-awning",
    source: "Striped café awning: green and white, a red price board.",
    ground: "white",
    temperature: "cool",
    stances: ["signage"],
    trades: ["bakery", "restaurant", "shop/deli"],
    mood: ["band", "bright", "cool"],
    colors: { background: "#ffffff", surface: "#eef5f1", text: "#18221d", muted: "#626965", primary: "#1e6b4a", onPrimary: "#ffffff", accent: "#d94b3f", border: "#dbe2de", inverse: "#12392a", onInverse: "#ecf5f2", band: "#c23b2f", onBand: "#ecf5f2" },
  },
  {
    id: "barber-pole",
    source: "Barber pole: red, white and blue.",
    ground: "white",
    temperature: "warm",
    stances: ["signage"],
    trades: ["hairdresser"],
    mood: ["band", "signal", "warm"],
    colors: { background: "#ffffff", surface: "#eef1f7", text: "#161a22", muted: "#63666b", primary: "#b3202a", onPrimary: "#ffffff", accent: "#3164bf", border: "#dde0e6", inverse: "#161a22", onInverse: "#f0f1f5", band: "#1f3d7a", onBand: "#f0f1f5" },
  },
  {
    id: "departure-board",
    source: "Airport departure board: signal blue and yellow.",
    ground: "tint",
    temperature: "cool",
    stances: ["signage"],
    trades: ["accountant", "car-repair"],
    mood: ["band", "cool", "signal"],
    colors: { background: "#e0edfb", surface: "#ecf3fc", text: "#13213a", muted: "#57647a", primary: "#0d4fa8", onPrimary: "#ffffff", accent: "#c43b2a", border: "#c7cfdb", inverse: "#13213a", onInverse: "#eef1f6", band: "#ffcf3a", onBand: "#13213a" },
  },
  {
    id: "beehive-panel",
    source: "Painted beehive panel (panjska končnica): pine green, vermilion, ochre.",
    ground: "white",
    temperature: "cool",
    stances: ["beehive-panel", "craft"],
    trades: ["bakery", "shop/deli", "tourist-farm"],
    mood: ["band", "bright", "cool", "earth"],
    colors: { background: "#ffffff", surface: "#edf3ec", text: "#241a12", muted: "#6c6660", primary: "#2d5e3e", onPrimary: "#ffffff", accent: "#d55241", border: "#dde2db", inverse: "#183a28", onInverse: "#ecf5f1", band: "#e1a83a", onBand: "#241a12" },
  },
  {
    id: "beehive-sky",
    source: "Beehive panel on a sky-blue ground, red and ochre figures.",
    ground: "tint",
    temperature: "warm",
    stances: ["beehive-panel", "craft"],
    trades: ["bakery", "shop/deli", "tourist-farm"],
    mood: ["band", "bright", "warm"],
    colors: { background: "#e5eff9", surface: "#eff5fb", text: "#1a2433", muted: "#5b6572", primary: "#b8322a", onPrimary: "#ffffff", accent: "#c8622a", border: "#cbd1d9", inverse: "#16294a", onInverse: "#eef1f6", band: "#3d7a46", onBand: "#eef1f6" },
  },
  {
    id: "dowry-chest",
    source: "Painted dowry chest: deep blue-green ground, ochre and red flowers.",
    ground: "dark",
    temperature: "warm",
    stances: ["craft", "beehive-panel"],
    trades: ["restaurant", "shop/deli", "tourist-farm"],
    mood: ["band", "bright", "deep", "warm"],
    colors: { background: "#10293a", surface: "#153246", text: "#eef1ee", muted: "#95a1a6", primary: "#e3a53c", onPrimary: "#10293a", accent: "#e46a4f", border: "#223d50", inverse: "#0a1d29", onInverse: "#eef3f6", band: "#c63f2f", onBand: "#eef3f6" },
  },
  {
    id: "idrija-lace",
    source: "Idrija bobbin lace: white thread on an indigo pillow, brass pins.",
    ground: "white",
    temperature: "cool",
    stances: ["craft"],
    trades: ["dental", "hairdresser", "shop/boutique"],
    mood: ["band", "cool", "deep", "two-colour"],
    colors: { background: "#ffffff", surface: "#eef0f7", text: "#1a1d2b", muted: "#63656f", primary: "#22306b", onPrimary: "#ffffff", accent: "#b98a2e", border: "#dfe1e9", inverse: "#171a2a", onInverse: "#eff0f6", band: "#22306b", onBand: "#eff0f6" },
  },
  {
    id: "licitar",
    source: "Licitar gingerbread heart: glossy red, white icing, green and yellow trim.",
    ground: "white",
    temperature: "warm",
    stances: ["craft"],
    trades: ["bakery", "shop/deli"],
    mood: ["band", "bright", "warm"],
    colors: { background: "#ffffff", surface: "#eef4ec", text: "#241417", muted: "#6e6466", primary: "#b3151b", onPrimary: "#ffffff", accent: "#bd8b23", border: "#dee2db", inverse: "#3a1214", onInverse: "#f6eeef", band: "#2f7c44", onBand: "#f6eeef" },
  },
  {
    id: "cut-paper",
    source: "Cut-paper collage in three primaries.",
    ground: "white",
    temperature: "warm",
    stances: ["craft", "colour-block"],
    trades: ["hairdresser", "shop/boutique", "shop/florist"],
    mood: ["band", "bright", "warm"],
    colors: { background: "#ffffff", surface: "#eef2f9", text: "#1d1d22", muted: "#656569", primary: "#d63a26", onPrimary: "#ffffff", accent: "#c48814", border: "#dde1e8", inverse: "#1d1d22", onInverse: "#f1f1f3", band: "#2c6bb5", onBand: "#f1f1f3" },
  },
  {
    id: "linocut",
    source: "Linocut print: black and one orange.",
    ground: "white",
    temperature: "warm",
    stances: ["craft", "print"],
    trades: ["bakery", "builder/carpentry", "shop/boutique"],
    mood: ["band", "monochrome", "two-colour", "warm"],
    colors: { background: "#ffffff", surface: "#f1f1f2", text: "#19181a", muted: "#676768", primary: "#19181a", onPrimary: "#ffffff", accent: "#e2572a", border: "#e0e0e1", inverse: "#19181a", onInverse: "#f2f2f3", band: "#e2572a", onBand: "#19181a" },
  },
  {
    id: "felt-wool",
    source: "Boiled-wool felt: rose and teal on a lavender-grey ground.",
    ground: "tint",
    temperature: "warm",
    stances: ["craft"],
    trades: ["hairdresser", "physio", "shop/boutique"],
    mood: ["band", "muted", "warm"],
    colors: { background: "#eceefa", surface: "#f4f5fc", text: "#22202e", muted: "#656471", primary: "#b23a55", onPrimary: "#ffffff", accent: "#3a7f6f", border: "#d0d1d9", inverse: "#22202e", onInverse: "#f1f0f5", band: "#f1b8c5", onBand: "#22202e" },
  },
  {
    id: "celadon-glaze",
    source: "Celadon and copper-green pottery glaze, an iron-brown rim.",
    ground: "white",
    temperature: "cool",
    stances: ["craft"],
    trades: ["physio", "restaurant", "shop/deli"],
    mood: ["band", "cool", "earth", "muted"],
    colors: { background: "#ffffff", surface: "#edf3ee", text: "#1b2420", muted: "#626865", primary: "#2e6b4f", onPrimary: "#ffffff", accent: "#b5752a", border: "#dce2de", inverse: "#173a2c", onInverse: "#ecf5f2", band: "#9cc4aa", onBand: "#1b2420" },
  },
  {
    id: "stencil-crate",
    source: "Stencilled wooden crate: army olive with orange lettering.",
    ground: "white",
    temperature: "cool",
    stances: ["craft", "signage"],
    trades: ["builder", "car-repair", "shop/deli"],
    mood: ["band", "cool", "earth"],
    colors: { background: "#ffffff", surface: "#eef1ec", text: "#1f2318", muted: "#646760", primary: "#4d5a2a", onPrimary: "#ffffff", accent: "#c8602a", border: "#dde1db", inverse: "#2a3016", onInverse: "#f2f4ea", band: "#d9b44a", onBand: "#1f2318" },
  },
  {
    id: "swiss-red",
    source: "International Typographic Style poster: black, white, one red.",
    ground: "white",
    temperature: "warm",
    stances: ["swiss-grid", "modernist"],
    trades: ["accountant", "builder", "car-repair"],
    mood: ["band", "monochrome", "signal", "two-colour", "warm"],
    colors: { background: "#ffffff", surface: "#f2f2f2", text: "#141414", muted: "#666666", primary: "#d81e17", onPrimary: "#ffffff", accent: "#e2352b", border: "#e0e0e0", inverse: "#141414", onInverse: "#f2f2f2", band: "#d81e17", onBand: "#f2f2f2" },
  },
  {
    id: "swiss-blue",
    source: "Transit signage: one pure blue on white.",
    ground: "white",
    temperature: "cool",
    stances: ["swiss-grid", "modernist"],
    trades: ["accountant", "dental", "physio"],
    mood: ["band", "cool", "monochrome"],
    colors: { background: "#ffffff", surface: "#eef2fa", text: "#10131a", muted: "#64666a", primary: "#0047bb", onPrimary: "#ffffff", accent: "#3d7bff", border: "#dce0e8", inverse: "#10131a", onInverse: "#eff1f5", band: "#0047bb", onBand: "#eff1f5" },
  },
  {
    id: "bauhaus",
    source: "Bauhaus primaries: blue, red, yellow on white.",
    ground: "white",
    temperature: "cool",
    stances: ["modernist", "colour-block"],
    trades: ["builder", "hairdresser", "shop/boutique"],
    mood: ["band", "bright", "cool"],
    colors: { background: "#ffffff", surface: "#f1f2f4", text: "#17181c", muted: "#666769", primary: "#1f3c8f", onPrimary: "#ffffff", accent: "#e03a2b", border: "#e0e1e3", inverse: "#17181c", onInverse: "#f1f2f3", band: "#f2c230", onBand: "#17181c" },
  },
  {
    id: "plecnik-stone",
    source: "Plečnik's Ljubljana: grey-green stone, oxblood, bronze.",
    ground: "tint",
    temperature: "warm",
    stances: ["plecnik-classicism", "modernist"],
    trades: ["accountant", "dental", "restaurant"],
    mood: ["band", "deep", "muted", "warm"],
    colors: { background: "#e1ece6", surface: "#ecf3ef", text: "#1f2622", muted: "#5b635f", primary: "#7a2a22", onPrimary: "#ffffff", accent: "#a06c22", border: "#c7ceca", inverse: "#1f2622", onInverse: "#f1f4f2", band: "#7d8f82", onBand: "#1f2622" },
  },
  {
    id: "plecnik-night",
    source: "A Plečnik bronze lamp post against the night street.",
    ground: "dark",
    temperature: "warm",
    stances: ["plecnik-classicism", "modernist"],
    trades: ["accountant", "hairdresser", "restaurant"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#161a1c", surface: "#1e2427", text: "#ecebe6", muted: "#929391", primary: "#c39a52", onPrimary: "#161a1c", accent: "#c39a52", border: "#2a3032", inverse: "#22292c", onInverse: "#f1f3f4", band: "#6e2a24", onBand: "#f1f3f4" },
  },
  {
    id: "yugo-poster",
    source: "Yugoslav modernist poster: orange and teal.",
    ground: "white",
    temperature: "warm",
    stances: ["modernist"],
    trades: ["physio", "restaurant", "shop"],
    mood: ["band", "bright", "two-colour", "warm"],
    colors: { background: "#ffffff", surface: "#e9f3f3", text: "#1b1f24", muted: "#64676a", primary: "#b84c0e", onPrimary: "#ffffff", accent: "#148a8a", border: "#d9e2e2", inverse: "#0d3838", onInverse: "#ecf5f5", band: "#e8641b", onBand: "#1b1f24" },
  },
  {
    id: "hotel-lobby",
    source: "1970s hotel lobby: walnut dark, orange, teal upholstery.",
    ground: "dark",
    temperature: "warm",
    stances: ["modernist"],
    trades: ["hairdresser", "restaurant", "tourist-farm"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#1a1410", surface: "#241c16", text: "#f0e9e0", muted: "#948d87", primary: "#e07a2e", onPrimary: "#1a1410", accent: "#e07a2e", border: "#342c26", inverse: "#2a201a", onInverse: "#f5f2ef", band: "#2f6d6a", onBand: "#f5f2ef" },
  },
  {
    id: "beton-brut",
    source: "Béton brut housing block: concrete grey, a red balcony panel.",
    ground: "tint",
    temperature: "warm",
    stances: ["modernist"],
    trades: ["accountant", "builder", "car-repair"],
    mood: ["band", "muted", "signal", "warm"],
    colors: { background: "#d9dee2", surface: "#e4e8eb", text: "#1a1d20", muted: "#575b5e", primary: "#b83e1b", onPrimary: "#ffffff", accent: "#2e69b3", border: "#c0c3c6", inverse: "#1a1d20", onInverse: "#f1f2f4", band: "#b83e1b", onBand: "#f1f2f4" },
  },
  {
    id: "gentian",
    source: "Gentian blue and larch green in an alpine meadow.",
    ground: "white",
    temperature: "cool",
    stances: ["nature", "place"],
    trades: ["physio", "tourist-farm"],
    mood: ["band", "bright", "cool"],
    colors: { background: "#ffffff", surface: "#e9eef9", text: "#19223a", muted: "#5e6475", primary: "#2b4aa8", onPrimary: "#ffffff", accent: "#3b8a52", border: "#dae0ec", inverse: "#172a66", onInverse: "#eef0f6", band: "#2b4aa8", onBand: "#eef0f6" },
  },
  {
    id: "karst-teran",
    source: "Karst: limestone grey, teran wine, terra rossa.",
    ground: "white",
    temperature: "warm",
    stances: ["karst-stone", "place"],
    trades: ["restaurant", "shop/deli", "tourist-farm"],
    mood: ["band", "deep", "earth", "warm"],
    colors: { background: "#ffffff", surface: "#ecedee", text: "#23211f", muted: "#656462", primary: "#6b1f2e", onPrimary: "#ffffff", accent: "#8d7a5a", border: "#e0e1e2", inverse: "#23211f", onInverse: "#f3f2f1", band: "#a9472a", onBand: "#f3f2f1" },
  },
  {
    id: "karst-night",
    source: "Karst stone wall at night: terra rossa, pale limestone.",
    ground: "dark",
    temperature: "warm",
    stances: ["karst-stone", "place"],
    trades: ["restaurant", "tourist-farm"],
    mood: ["band", "deep", "earth", "warm"],
    colors: { background: "#1b1a19", surface: "#252321", text: "#ecebe7", muted: "#949390", primary: "#cb654c", onPrimary: "#1b1a19", accent: "#c9b28a", border: "#312f2d", inverse: "#2a2826", onInverse: "#f3f2f2", band: "#6b1f2e", onBand: "#f3f2f2" },
  },
  {
    id: "vineyard-rows",
    source: "Vineyard rows in September: vine green, red wine.",
    ground: "white",
    temperature: "warm",
    stances: ["nature", "place"],
    trades: ["restaurant", "shop/deli", "tourist-farm"],
    mood: ["band", "earth", "warm"],
    colors: { background: "#ffffff", surface: "#eff3e6", text: "#20181a", muted: "#6a6466", primary: "#5d1f2b", onPrimary: "#ffffff", accent: "#6f8f3a", border: "#dee1d6", inverse: "#3a121b", onInverse: "#f6eef0", band: "#c9d68f", onBand: "#20181a" },
  },
  {
    id: "soca",
    source: "The Soča's emerald water over white pebbles.",
    ground: "tint",
    temperature: "cool",
    stances: ["nature", "place"],
    trades: ["dental", "physio", "tourist-farm"],
    mood: ["band", "bright", "cool"],
    colors: { background: "#dff2ef", surface: "#edf8f6", text: "#0f2a2a", muted: "#4f6867", primary: "#0b6f6b", onPrimary: "#ffffff", accent: "#0e837d", border: "#c7d5d3", inverse: "#0d2b2c", onInverse: "#ecf5f5", band: "#13a39a", onBand: "#0f2a2a" },
  },
  {
    id: "lake-bled",
    source: "Lake Bled: cold blue water, the island church's orange roof.",
    ground: "tint",
    temperature: "cool",
    stances: ["nature", "place"],
    trades: ["physio", "restaurant", "tourist-farm"],
    mood: ["band", "cool", "two-colour"],
    colors: { background: "#e3edf7", surface: "#eef4fa", text: "#142638", muted: "#546473", primary: "#1e5b8c", onPrimary: "#ffffff", accent: "#b8621f", border: "#c9d1d9", inverse: "#142638", onInverse: "#eef2f6", band: "#1e5b8c", onBand: "#eef2f6" },
  },
  {
    id: "kozolec",
    source: "Hayrack (kozolec): weathered wood, dry hay, grass.",
    ground: "white",
    temperature: "warm",
    stances: ["nature", "craft"],
    trades: ["bakery", "builder/carpentry", "tourist-farm"],
    mood: ["band", "earth", "warm"],
    colors: { background: "#ffffff", surface: "#eef2e8", text: "#22180f", muted: "#6b645e", primary: "#6b4226", onPrimary: "#ffffff", accent: "#4f7a2f", border: "#dee1d7", inverse: "#2a1d13", onInverse: "#f6f2ee", band: "#e3b84c", onBand: "#22180f" },
  },
  {
    id: "salt-pans",
    source: "Sečovlje salt pans: grey-blue water, white salt, rusty sluice gates.",
    ground: "tint",
    temperature: "cool",
    stances: ["nature", "place"],
    trades: ["restaurant", "shop/deli", "tourist-farm"],
    mood: ["band", "cool", "muted"],
    colors: { background: "#e5edf5", surface: "#f0f5f9", text: "#18242f", muted: "#5a646e", primary: "#31607f", onPrimary: "#ffffff", accent: "#b8603a", border: "#cbd1d7", inverse: "#18242f", onInverse: "#eef2f6", band: "#a8552f", onBand: "#eef2f6" },
  },
  {
    id: "olive-grove",
    source: "Istrian olive grove: olive green, silver leaf, oil gold.",
    ground: "white",
    temperature: "warm",
    stances: ["nature", "place"],
    trades: ["restaurant", "shop/deli", "tourist-farm"],
    mood: ["band", "earth", "muted", "warm"],
    colors: { background: "#ffffff", surface: "#eef1ea", text: "#22251a", muted: "#64665f", primary: "#5f6b2a", onPrimary: "#ffffff", accent: "#a08a32", border: "#dee1d9", inverse: "#2b3013", onInverse: "#f3f4ea", band: "#5f6b2a", onBand: "#f3f4ea" },
  },
  {
    id: "pumpkin-oil",
    source: "Pumpkin-seed oil: green-black in the bottle, gold in the light.",
    ground: "dark",
    temperature: "warm",
    stances: ["nature", "place"],
    trades: ["restaurant", "shop/deli", "tourist-farm"],
    mood: ["band", "deep", "earth", "warm"],
    colors: { background: "#121a10", surface: "#19241a", text: "#eef0e6", muted: "#8d9288", primary: "#d9a22f", onPrimary: "#121a10", accent: "#d98b2b", border: "#283228", inverse: "#1c2a16", onInverse: "#f0f5ec", band: "#4b6b2a", onBand: "#f0f5ec" },
  },
  {
    id: "harbour-night",
    source: "Harbour at night: dark sea, a lamp's orange.",
    ground: "dark",
    temperature: "warm",
    stances: ["nature", "place"],
    trades: ["restaurant"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#0d1b2a", surface: "#13243a", text: "#e9eef3", muted: "#8a939d", primary: "#f2a65a", onPrimary: "#0d1b2a", accent: "#f2a65a", border: "#203045", inverse: "#112a42", onInverse: "#eef2f6", band: "#2b6f97", onBand: "#eef2f6" },
  },
  {
    id: "glacier",
    source: "Glacier ice and meltwater blue.",
    ground: "tint",
    temperature: "cool",
    stances: ["nature"],
    trades: ["dental", "physio", "tourist-farm"],
    mood: ["band", "cool", "monochrome"],
    colors: { background: "#e1f0f7", surface: "#eef7fb", text: "#10283a", muted: "#516675", primary: "#13557a", onPrimary: "#ffffff", accent: "#24789b", border: "#c6d2d8", inverse: "#10283a", onInverse: "#eef3f6", band: "#9ed0e6", onBand: "#10283a" },
  },
  {
    id: "cornflower-rye",
    source: "Cornflowers and poppies in a rye field.",
    ground: "white",
    temperature: "cool",
    stances: ["nature"],
    trades: ["bakery", "shop/florist", "tourist-farm"],
    mood: ["band", "bright", "cool"],
    colors: { background: "#ffffff", surface: "#ecf0fb", text: "#1a1f33", muted: "#616472", primary: "#3552b8", onPrimary: "#ffffff", accent: "#9d6b18", border: "#dde1ed", inverse: "#1a2660", onInverse: "#eef0f6", band: "#c8342a", onBand: "#eef0f6" },
  },
  {
    id: "damson",
    source: "Damson plums (slive) and their dusty bloom.",
    ground: "tint",
    temperature: "cool",
    stances: ["nature"],
    trades: ["bakery", "shop/deli", "tourist-farm"],
    mood: ["band", "cool", "deep", "muted"],
    colors: { background: "#efe6f2", surface: "#f6f0f8", text: "#2a1730", muted: "#6b5b70", primary: "#6a2a6e", onPrimary: "#ffffff", accent: "#b0602a", border: "#d3cbd6", inverse: "#2a1730", onInverse: "#f4eef6", band: "#d4b0da", onBand: "#2a1730" },
  },
  {
    id: "rose-hip",
    source: "Rose-hips on a bare branch.",
    ground: "white",
    temperature: "warm",
    stances: ["nature"],
    trades: ["shop/deli", "shop/florist"],
    mood: ["band", "earth", "warm"],
    colors: { background: "#ffffff", surface: "#f8ecea", text: "#2a1612", muted: "#6e615e", primary: "#a8321e", onPrimary: "#ffffff", accent: "#51703d", border: "#eadddb", inverse: "#2a1612", onInverse: "#f6f0ee", band: "#e8a08a", onBand: "#2a1612" },
  },
  {
    id: "farmyard",
    source: "Farmyard: meadow green, a red barn door, straw.",
    ground: "white",
    temperature: "cool",
    stances: ["nature", "seed-packet"],
    trades: ["tourist-farm"],
    mood: ["band", "bright", "cool", "earth"],
    colors: { background: "#ffffff", surface: "#eef4e8", text: "#1f2617", muted: "#64695f", primary: "#3f6b2a", onPrimary: "#ffffff", accent: "#c18923", border: "#dde4d7", inverse: "#1c3318", onInverse: "#eff5ec", band: "#a8322a", onBand: "#eff5ec" },
  },
  {
    id: "pink-bottle-green",
    source: "Colour-block shop window: hot pink against bottle green.",
    ground: "white",
    temperature: "warm",
    stances: ["colour-block", "contemporary"],
    trades: ["hairdresser", "shop/boutique", "shop/florist"],
    mood: ["band", "bright", "two-colour", "warm"],
    colors: { background: "#ffffff", surface: "#eef6f2", text: "#1d1720", muted: "#6a666c", primary: "#c42b62", onPrimary: "#ffffff", accent: "#e0457f", border: "#dbe2df", inverse: "#0f3a2a", onInverse: "#ecf5f2", band: "#1f7a5a", onBand: "#ecf5f2" },
  },
  {
    id: "editorial-mono",
    source: "Magazine spread: black type, one red rule.",
    ground: "white",
    temperature: "neutral",
    stances: ["editorial-magazine", "contemporary"],
    trades: ["accountant", "dental", "hairdresser"],
    mood: ["monochrome", "neutral"],
    colors: { background: "#ffffff", surface: "#f0f0f0", text: "#151515", muted: "#656565", primary: "#151515", onPrimary: "#ffffff", accent: "#d14a4a", border: "#e1e1e1", inverse: "#151515", onInverse: "#f2f2f2" },
  },
  {
    id: "editorial-blush",
    source: "Fashion supplement: blush paper, ink, a blue headline.",
    ground: "tint",
    temperature: "warm",
    stances: ["editorial-magazine", "contemporary"],
    trades: ["hairdresser", "shop/boutique"],
    mood: ["two-colour", "warm"],
    colors: { background: "#f9e6e1", surface: "#fcf0ec", text: "#2b1a1a", muted: "#6f5d5c", primary: "#2b1a1a", onPrimary: "#ffffff", accent: "#3269ba", border: "#d8ccc8", inverse: "#2b1a1a", onInverse: "#f5efef" },
  },
  {
    id: "ink-blue-page",
    source: "An oversized blue headline on a pale blue page.",
    ground: "tint",
    temperature: "cool",
    stances: ["contemporary", "editorial-magazine"],
    trades: ["accountant", "dental", "physio"],
    mood: ["band", "cool", "monochrome", "two-colour"],
    colors: { background: "#e6ebfa", surface: "#f0f3fc", text: "#121a3a", muted: "#5a617b", primary: "#2333a8", onPrimary: "#ffffff", accent: "#d84f36", border: "#cacedb", inverse: "#121a3a", onInverse: "#eef0f6", band: "#2333a8", onBand: "#eef0f6" },
  },
  {
    id: "photo-book",
    source: "Black-and-white photo book with one red caption.",
    ground: "dark",
    temperature: "neutral",
    stances: ["editorial-magazine", "contemporary"],
    trades: ["builder", "hairdresser", "restaurant"],
    mood: ["deep", "monochrome", "neutral"],
    colors: { background: "#141414", surface: "#1c1c1c", text: "#ececec", muted: "#8b8b8b", primary: "#ececec", onPrimary: "#141414", accent: "#e5534b", border: "#2b2b2b", inverse: "#242424", onInverse: "#f2f2f2" },
  },
  {
    id: "regatta",
    source: "Regatta flags: navy and coral.",
    ground: "white",
    temperature: "cool",
    stances: ["contemporary", "colour-block"],
    trades: ["dental", "physio", "restaurant"],
    mood: ["band", "cool", "two-colour"],
    colors: { background: "#ffffff", surface: "#eef1f7", text: "#141d33", muted: "#5f6574", primary: "#1b2b52", onPrimary: "#ffffff", accent: "#e05a47", border: "#dde0e7", inverse: "#141d33", onInverse: "#eef1f6", band: "#e05a47", onBand: "#141d33" },
  },
  {
    id: "surgery-mint",
    source: "Treatment room: mint wall, teal tiles, a blue floor line.",
    ground: "tint",
    temperature: "cool",
    stances: ["contemporary"],
    trades: ["dental", "physio"],
    mood: ["band", "cool", "muted"],
    colors: { background: "#e3f4ef", surface: "#eef9f5", text: "#0f2a28", muted: "#536b68", primary: "#0f6b62", onPrimary: "#ffffff", accent: "#3c6ec7", border: "#c8d6d2", inverse: "#0f2a28", onInverse: "#ecf5f5", band: "#0f6b62", onBand: "#ecf5f5" },
  },
  {
    id: "salon-noir",
    source: "Salon at night: black mirror glass, powder pink.",
    ground: "dark",
    temperature: "warm",
    stances: ["contemporary", "editorial-magazine"],
    trades: ["hairdresser", "shop/boutique"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#161215", surface: "#201a1e", text: "#f2ecee", muted: "#8f8a8c", primary: "#e7a6b8", onPrimary: "#161215", accent: "#e7a6b8", border: "#2f292d", inverse: "#2a1f25", onInverse: "#f4f0f2", band: "#6b2a3e", onBand: "#f4f0f2" },
  },
  {
    id: "salon-chair",
    source: "A powder-pink salon chair, plum lettering.",
    ground: "white",
    temperature: "warm",
    stances: ["contemporary"],
    trades: ["hairdresser", "shop/boutique", "shop/florist"],
    mood: ["band", "muted", "warm"],
    colors: { background: "#ffffff", surface: "#f8ecef", text: "#2a1a20", muted: "#6e6367", primary: "#9b3b5a", onPrimary: "#ffffff", accent: "#c45a7a", border: "#eadde1", inverse: "#3a1a2a", onInverse: "#f6eef2", band: "#f3c9d4", onBand: "#2a1a20" },
  },
  {
    id: "bakery-blue",
    source: "A bakery fascia painted blue, a crust-gold board.",
    ground: "white",
    temperature: "cool",
    stances: ["signage", "craft"],
    trades: ["bakery", "shop/deli"],
    mood: ["band", "cool", "two-colour"],
    colors: { background: "#ffffff", surface: "#eaf0f8", text: "#141d2e", muted: "#5f6571", primary: "#24427a", onPrimary: "#ffffff", accent: "#c4682a", border: "#dbe1ea", inverse: "#142a52", onInverse: "#eef1f6", band: "#f0c75e", onBand: "#141d2e" },
  },
  {
    id: "butcher-tile",
    source: "Butcher's shop: white tiles, oxblood, a green trim.",
    ground: "white",
    temperature: "warm",
    stances: ["craft"],
    trades: ["restaurant", "shop/deli"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#ffffff", surface: "#edf4f0", text: "#1c1415", muted: "#6b6667", primary: "#8a1c24", onPrimary: "#ffffff", accent: "#2f7a5a", border: "#dce2de", inverse: "#3a0e13", onInverse: "#f6eeef", band: "#8a1c24", onBand: "#f6eeef" },
  },
  {
    id: "overalls",
    source: "Workshop overalls: navy cloth, a yellow tape measure.",
    ground: "dark",
    temperature: "cool",
    stances: ["workshop-docket"],
    trades: ["builder", "car-repair"],
    mood: ["band", "cool", "deep", "signal"],
    colors: { background: "#121821", surface: "#19212c", text: "#e9eef4", muted: "#8a9097", primary: "#5b9bf0", onPrimary: "#121821", accent: "#f2b33d", border: "#282f3a", inverse: "#1c2633", onInverse: "#eff2f6", band: "#f2b33d", onBand: "#121821" },
  },
  {
    id: "cable-colours",
    source: "Cable colours: brown live, blue neutral, a yellow cable tie.",
    ground: "white",
    temperature: "warm",
    stances: ["workshop-docket"],
    trades: ["builder/electrical"],
    mood: ["band", "signal", "warm"],
    colors: { background: "#ffffff", surface: "#eef2f8", text: "#15191f", muted: "#65676b", primary: "#6e3b1c", onPrimary: "#ffffff", accent: "#b07d12", border: "#dde1e7", inverse: "#15191f", onInverse: "#f0f2f5", band: "#1f4fa3", onBand: "#f0f2f5" },
  },
  {
    id: "slate-roof",
    source: "A slate roof with clay ridge tiles.",
    ground: "tint",
    temperature: "cool",
    stances: ["place"],
    trades: ["builder", "builder/roofing"],
    mood: ["band", "cool", "muted"],
    colors: { background: "#e5ecf2", surface: "#eff3f7", text: "#1c242c", muted: "#5c646b", primary: "#3b4a59", onPrimary: "#ffffff", accent: "#b5552a", border: "#cbd0d4", inverse: "#1c242c", onInverse: "#eff2f5", band: "#9fb2c3", onBand: "#1c242c" },
  },
  {
    id: "oak-workshop",
    source: "Oak boards, linseed oil, a green workshop wall.",
    ground: "white",
    temperature: "warm",
    stances: ["craft"],
    trades: ["builder", "builder/carpentry"],
    mood: ["band", "earth", "warm"],
    colors: { background: "#ffffff", surface: "#eef2ec", text: "#22180f", muted: "#6b645e", primary: "#7a4a22", onPrimary: "#ffffff", accent: "#bf893a", border: "#dee1da", inverse: "#1e3020", onInverse: "#eff5f0", band: "#4f6f3a", onBand: "#eff5f0" },
  },
  {
    id: "peony",
    source: "Peonies in a zinc bucket: pink petals, leaf green.",
    ground: "tint",
    temperature: "warm",
    stances: ["nature"],
    trades: ["shop/florist"],
    mood: ["band", "bright", "warm"],
    colors: { background: "#fae8ee", surface: "#fdf2f6", text: "#2a1720", muted: "#715e66", primary: "#a3264f", onPrimary: "#ffffff", accent: "#3e7d4a", border: "#d9cdd2", inverse: "#2a1720", onInverse: "#f6eff2", band: "#f2a7bf", onBand: "#2a1720" },
  },
  {
    id: "boutique-night",
    source: "Boutique window at night: ink, sand, a wine ribbon.",
    ground: "dark",
    temperature: "warm",
    stances: ["contemporary"],
    trades: ["hairdresser", "shop/boutique"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#12141c", surface: "#1a1d27", text: "#eceef4", muted: "#8a8c93", primary: "#d7b98e", onPrimary: "#12141c", accent: "#d7b98e", border: "#292c35", inverse: "#1e2230", onInverse: "#eff1f5", band: "#8a2c3c", onBand: "#eff1f5" },
  },
  {
    id: "graphite-tick",
    source: "Graphite pencil and a green tick.",
    ground: "white",
    temperature: "cool",
    stances: ["swiss-grid"],
    trades: ["accountant", "dental"],
    mood: ["band", "cool", "monochrome"],
    colors: { background: "#ffffff", surface: "#eff1f2", text: "#1d2125", muted: "#636669", primary: "#2e3338", onPrimary: "#ffffff", accent: "#2a8a5a", border: "#dee0e2", inverse: "#1d2125", onInverse: "#f1f2f4", band: "#267d52", onBand: "#f1f2f4" },
  },
  {
    id: "check-tablecloth",
    source: "Red check tablecloth and a green bottle.",
    ground: "white",
    temperature: "warm",
    stances: ["craft"],
    trades: ["restaurant"],
    mood: ["band", "two-colour", "warm"],
    colors: { background: "#ffffff", surface: "#f6ecec", text: "#22191a", muted: "#696363", primary: "#b51f2a", onPrimary: "#ffffff", accent: "#e0533f", border: "#e9dfdf", inverse: "#163a26", onInverse: "#ecf5f1", band: "#b51f2a", onBand: "#ecf5f1" },
  },
  {
    id: "wine-cellar",
    source: "Wine cellar: wine-black, candle gold, a red label.",
    ground: "dark",
    temperature: "warm",
    stances: ["karst-stone"],
    trades: ["restaurant", "shop/deli"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#1a1315", surface: "#231a1d", text: "#f3ebe8", muted: "#918a89", primary: "#e0b25a", onPrimary: "#1a1315", accent: "#e0b25a", border: "#342b2d", inverse: "#2a1d21", onInverse: "#f5f0f1", band: "#7a2333", onBand: "#f5f0f1" },
  },
  {
    id: "fountain-pen",
    source: "Fountain-pen ink and a brass desk lamp.",
    ground: "dark",
    temperature: "cool",
    stances: ["print"],
    trades: ["accountant"],
    mood: ["band", "cool", "deep"],
    colors: { background: "#0f1828", surface: "#152035", text: "#e9edf3", muted: "#898f9a", primary: "#8fb4ef", onPrimary: "#0f1828", accent: "#d4a95a", border: "#242e42", inverse: "#172338", onInverse: "#eef1f6", band: "#d4a95a", onBand: "#0f1828" },
  },
  {
    id: "red-pencil",
    source: "Charcoal sketch with a red pencil.",
    ground: "dark",
    temperature: "warm",
    stances: ["swiss-grid", "contemporary"],
    trades: ["accountant", "builder", "car-repair"],
    mood: ["band", "monochrome", "signal", "warm"],
    colors: { background: "#18191b", surface: "#202124", text: "#eceef0", muted: "#8f9092", primary: "#ff6a5a", onPrimary: "#18191b", accent: "#ff6a5a", border: "#2e2f32", inverse: "#26282b", onInverse: "#f1f2f3", band: "#ff6a5a", onBand: "#18191b" },
  },
  {
    id: "copper-slate",
    source: "Copper pipe against wet slate.",
    ground: "dark",
    temperature: "warm",
    stances: ["craft"],
    trades: ["builder", "builder/plumbing"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#161c22", surface: "#1d252d", text: "#e8edf1", muted: "#8e9398", primary: "#d98a5a", onPrimary: "#161c22", accent: "#d98a5a", border: "#293139", inverse: "#1f2a33", onInverse: "#eff3f5", band: "#3c5568", onBand: "#eff3f5" },
  },
  {
    id: "night-pool",
    source: "Night swimming pool: teal water, a yellow lifebuoy.",
    ground: "dark",
    temperature: "cool",
    stances: ["contemporary"],
    trades: ["dental", "hairdresser", "physio"],
    mood: ["band", "cool", "deep"],
    colors: { background: "#0e1f24", surface: "#142a30", text: "#e6f0f0", muted: "#8b989a", primary: "#4fc1b0", onPrimary: "#0e1f24", accent: "#f2b45c", border: "#21363c", inverse: "#123037", onInverse: "#ecf4f5", band: "#1c5a63", onBand: "#ecf4f5" },
  },
  {
    id: "aubergine",
    source: "Aubergine skin and a saffron flame.",
    ground: "dark",
    temperature: "warm",
    stances: ["contemporary"],
    trades: ["hairdresser", "restaurant"],
    mood: ["band", "deep", "warm"],
    colors: { background: "#1c1220", surface: "#26182b", text: "#f0e8f2", muted: "#938a96", primary: "#e6a04f", onPrimary: "#1c1220", accent: "#e6a04f", border: "#36293b", inverse: "#2a1a30", onInverse: "#f4eef6", band: "#5a2a5e", onBand: "#f4eef6" },
  },
  {
    id: "bathing-poster",
    source: "Bathing-place poster: a sky-blue ground printed in navy and red.",
    ground: "tint",
    temperature: "cool",
    stances: ["colour-block", "print", "contemporary"],
    trades: ["physio", "restaurant", "tourist-farm"],
    mood: ["band", "bright", "cool", "two-colour"],
    colors: { background: "#b9d7ef", surface: "#cfe3f4", text: "#0f1f3a", muted: "#425670", primary: "#14306b", onPrimary: "#ffffff", accent: "#c83024", border: "#a9bccf", inverse: "#0f1f3a", onInverse: "#eef1f6", band: "#cd3326", onBand: "#eef1f6" },
  },
  {
    id: "mint-kiosk",
    source: "Newspaper kiosk painted mint green, red price tags.",
    ground: "tint",
    temperature: "cool",
    stances: ["signage", "colour-block"],
    trades: ["bakery", "shop", "shop/deli"],
    mood: ["band", "bright", "cool", "two-colour"],
    colors: { background: "#cdeadb", surface: "#dcf1e6", text: "#10261c", muted: "#4b6357", primary: "#0e5a3c", onPrimary: "#ffffff", accent: "#cb303e", border: "#b7ccc2", inverse: "#10261c", onInverse: "#ecf5f2", band: "#b02a36", onBand: "#ecf5f2" },
  },
];
