import type { Direction } from "./design.ts";

/**
 * Curated design directions. Each must look clearly different from the others on the eval contact sheet
 * (typography, colour mood, light/tinted/dark page, radius, density, imagery, section rhythm).
 * Fallback colours must pass every contrast rule in design-rules.ts (packages/spec/test/directions.test.ts checks this).
 */
export const DIRECTIONS: Direction[] = [
  {
    id: "clean-swiss",
    name: "Clean Swiss",
    summary:
      "White page, tight grotesk headings, strict left-aligned grid, square corners, one saturated brand colour used sparingly. Precise and calm. Choose for accountants, clinics and installers who want to look orderly and exact.",
    bestFor: ["accountant", "dental", "physio", "builder"],
    fontPairs: ["inter-tight-inter"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f1f4f8",
        text: "#111418",
        muted: "#4a5360",
        primary: "#1d4ed8",
        onPrimary: "#ffffff",
        accent: "#2563eb",
        border: "#d5dbe3",
        inverse: "#111418",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.45, 0.95],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [16, 17],
      scale: [1.2, 1.3],
      headingWeight: [600, 750],
      headingTracking: [-0.02, -0.005],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    layout: {
      header: "bar",
      footer: "columns",
      heroes: ["hero-split:image-right", "hero-type:with-facts"],
      rhythm: "flat",
      prefer: ["services-list:rows", "price-list:table", "faq:accordion", "opening-hours:table", "contact:split-map"],
    },
  },
  {
    id: "warm-craft",
    name: "Warm Craft",
    summary:
      "White page with a soft, characterful serif (Fraunces) in headings, terracotta or brand colour for buttons, photos set on an offset colour block, cool pale sage alternate sections. Warm and hand-made without cream backgrounds. Choose for bakeries, gostilne, family restaurants and small food shops with good product photos.",
    bestFor: ["bakery", "restaurant", "shop", "tourist-farm"],
    fontPairs: ["fraunces-source-sans", "bitter-nunito-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#edf2ef",
        text: "#221b17",
        muted: "#5b504a",
        primary: "#b4441f",
        onPrimary: "#ffffff",
        accent: "#c65a2e",
        border: "#d9e0dc",
        inverse: "#2b211c",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.4, 0.85],
    },
    ranges: {
      radius: [4, 8],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [550, 700],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none", "subtle"],
    },
    imagery: "offset-block",
    layout: {
      header: "split-cta",
      footer: "columns",
      heroes: ["hero-split:image-left", "hero-image:overlay-bottom"],
      rhythm: "alternate",
      prefer: ["menu:classic", "products:grid", "image-text:image-left", "opening-hours:compact", "gallery:mosaic", "about:image-side"],
    },
  },
  {
    id: "dark-elegant",
    name: "Dark Elegant",
    summary:
      "Near-black warm page, light high-contrast Garamond headings with generous spacing, brass accents, photos in thin frames, airy sections. Evening mood. Choose for restaurants, wine bars and upscale salons with atmospheric interior or food photos; avoid when photos are dark or few.",
    bestFor: ["restaurant", "hairdresser"],
    fontPairs: ["garamond-karla"],
    palette: {
      background: "dark",
      fallback: {
        background: "#14110f",
        surface: "#1f1a17",
        text: "#f2ece5",
        muted: "#b9ada1",
        primary: "#c9a46a",
        onPrimary: "#14110f",
        accent: "#c9a46a",
        border: "#3a322b",
        inverse: "#3a1d25",
        onInverse: "#f2ece5",
      },
      primaryHue: [25, 50],
      primarySaturation: [0.3, 0.6],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [17, 18],
      scale: [1.28, 1.36],
      headingWeight: [500, 600],
      headingTracking: [-0.01, 0.01],
      headingCase: ["normal"],
      density: ["airy"],
      shadow: ["none"],
    },
    imagery: "framed",
    layout: {
      header: "stacked",
      footer: "compact",
      heroes: ["hero-image:overlay-left", "hero-type:large"],
      rhythm: "alternate",
      prefer: ["menu:two-column", "image-text:image-right", "gallery:grid", "booking:with-hours", "about:image-side", "contact:stacked"],
    },
  },
  {
    id: "bold-local",
    name: "Bold Local",
    summary:
      "White page with heavy, compact Archivo headings (uppercase allowed), square corners, a loud signal colour for buttons and full-width near-black bands for key facts. Direct and practical, built for the phone number. Choose for car repair, tyre shops, builders and trades that sell reliability and speed.",
    bestFor: ["car-repair", "builder", "shop"],
    fontPairs: ["archivo-archivo"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#eef0f3",
        text: "#0e0f12",
        muted: "#474c55",
        primary: "#c8261b",
        onPrimary: "#ffffff",
        accent: "#e0301e",
        border: "#d3d7dd",
        inverse: "#111317",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.6, 1],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [16, 17],
      scale: [1.25, 1.333],
      headingWeight: [700, 850],
      headingTracking: [-0.02, 0.01],
      headingCase: ["uppercase", "normal"],
      density: ["compact", "regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    layout: {
      header: "split-cta",
      footer: "columns",
      heroes: ["hero-type:with-facts", "hero-split:image-right"],
      rhythm: "inverse-accents",
      prefer: ["contact-strip:bar", "services-cards:compact", "cta:band", "service-area:inline", "steps:horizontal", "price-list:table"],
    },
  },
  {
    id: "clinical-calm",
    name: "Clinical Calm",
    summary:
      "Pale cool-blue page with white cards, friendly geometric sans headings, softly rounded corners and photos, lots of air. Reassuring and clean without looking sterile. Choose for dental and physio practices and other health services where trust and easy booking matter.",
    bestFor: ["dental", "physio", "accountant"],
    fontPairs: ["manrope-public-sans", "inter-tight-inter"],
    palette: {
      background: "tint",
      fallback: {
        background: "#f1f6fb",
        surface: "#ffffff",
        text: "#102230",
        muted: "#4a5d6b",
        primary: "#0e6a88",
        onPrimary: "#ffffff",
        accent: "#1479a0",
        border: "#d3e0ea",
        inverse: "#0c2331",
        onInverse: "#f5f5f5",
      },
      primaryHue: [175, 225],
      primarySaturation: [0.35, 0.85],
    },
    ranges: {
      radius: [8, 12],
      baseFontSize: [17, 18],
      scale: [1.2, 1.25],
      headingWeight: [600, 750],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["airy", "regular"],
      shadow: ["subtle", "none"],
    },
    imagery: "rounded",
    layout: {
      header: "bar",
      footer: "columns",
      heroes: ["hero-split:image-right", "hero-type:with-facts"],
      rhythm: "alternate",
      prefer: ["booking:with-hours", "services-list:two-column", "team:grid", "faq:accordion", "opening-hours:table", "steps:vertical"],
    },
  },
  {
    id: "alpine-nature",
    name: "Alpine Nature",
    summary:
      "Pale green-tinted page, sturdy slab-serif headings, forest-green buttons, photos running edge to edge on phones. Outdoorsy and honest. Choose for tourist farms, mountain huts, gostilne in the countryside and anything sold on landscape, rooms and home-grown food.",
    bestFor: ["tourist-farm", "restaurant", "bakery"],
    fontPairs: ["bitter-nunito-sans", "fraunces-source-sans"],
    palette: {
      background: "tint",
      fallback: {
        background: "#eef5ef",
        surface: "#ffffff",
        text: "#13261a",
        muted: "#44574a",
        primary: "#2d6a3a",
        onPrimary: "#ffffff",
        accent: "#3a8049",
        border: "#cfdcd2",
        inverse: "#12241a",
        onInverse: "#f5f5f5",
      },
      primaryHue: [80, 170],
      primarySaturation: [0.25, 0.7],
    },
    ranges: {
      radius: [2, 6],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [600, 750],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "full-bleed",
    layout: {
      header: "bar",
      footer: "columns",
      heroes: ["hero-image:overlay-bottom", "hero-split:image-left"],
      rhythm: "alternate",
      prefer: ["rooms:cards", "gallery:mosaic", "image-text:image-left", "opening-hours:compact", "contact:split-map", "highlights:columns"],
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    summary:
      "White page led by large, light serif headlines like a quality newspaper, restrained sans body text, square framed photos, generous whitespace and one deep ink-red colour. Typography does the work. Choose for accountants, advisers and practices with few photos, or any client whose text is stronger than their pictures.",
    bestFor: ["accountant", "physio", "dental"],
    fontPairs: ["newsreader-libre-franklin", "garamond-karla"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f2f3f5",
        text: "#16161a",
        muted: "#55555f",
        primary: "#8f1d24",
        onPrimary: "#ffffff",
        accent: "#c23a3a",
        border: "#d9d9de",
        inverse: "#16161a",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.3, 0.8],
    },
    ranges: {
      radius: [0, 0],
      baseFontSize: [18, 19],
      scale: [1.333, 1.414],
      headingWeight: [400, 500],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["airy"],
      shadow: ["none"],
    },
    imagery: "framed",
    layout: {
      header: "stacked",
      footer: "columns",
      heroes: ["hero-type:large", "page-header:plain"],
      rhythm: "flat",
      prefer: ["text:two-column", "highlights:list", "services-list:rows", "faq:list", "team:list", "about:text-only"],
    },
  },
  {
    id: "playful-modern",
    name: "Playful Modern",
    summary:
      "White page with chunky, quirky grotesk headings, bright berry colour, pale lilac bands, the most rounded corners allowed and arch-topped photos. Friendly and current. Choose for bakeries, hairdressers, gift and concept shops aimed at a younger local crowd.",
    bestFor: ["bakery", "hairdresser", "shop"],
    fontPairs: ["bricolage-figtree"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f1edfc",
        text: "#1c1427",
        muted: "#554d66",
        primary: "#b01f5c",
        onPrimary: "#ffffff",
        accent: "#d93f7d",
        border: "#dcd5ee",
        inverse: "#2a1236",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.55, 1],
    },
    ranges: {
      radius: [10, 12],
      baseFontSize: [16, 17],
      scale: [1.25, 1.333],
      headingWeight: [700, 800],
      headingTracking: [-0.02, -0.005],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none", "subtle"],
    },
    imagery: "arched",
    layout: {
      header: "split-cta",
      footer: "compact",
      heroes: ["hero-split:image-right", "hero-type:large"],
      rhythm: "alternate",
      prefer: ["products:grid", "services-cards:grid", "price-list:grouped", "announcement:card", "gallery:grid", "team:grid"],
    },
  },
  {
    id: "industrial",
    name: "Industrial",
    summary:
      "Dark graphite page, technical grotesk headings, safety-yellow buttons and rules, black-and-white photos, square corners and dense spacing. Tough and no-nonsense. Choose for builders, installers, electricians, workshops and car repair with work-site photos.",
    bestFor: ["builder", "car-repair"],
    fontPairs: ["space-grotesk-plex", "archivo-archivo"],
    palette: {
      background: "dark",
      fallback: {
        background: "#15171a",
        surface: "#1e2125",
        text: "#eef0f2",
        muted: "#a7adb4",
        primary: "#f2c200",
        onPrimary: "#15171a",
        accent: "#f2c200",
        border: "#363a40",
        inverse: "#2b2f35",
        onInverse: "#f5f5f5",
      },
      primaryHue: [40, 55],
      primarySaturation: [0.8, 1],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [16, 17],
      scale: [1.2, 1.28],
      headingWeight: [600, 700],
      headingTracking: [-0.02, 0.02],
      headingCase: ["normal", "uppercase"],
      density: ["compact"],
      shadow: ["none"],
    },
    imagery: "monochrome",
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-image:overlay-bottom", "hero-type:with-facts"],
      rhythm: "inverse-accents",
      prefer: ["services-list:two-column", "steps:horizontal", "service-area:list", "gallery:mosaic", "contact-strip:cards", "cta:split"],
    },
  },
  {
    id: "soft-studio",
    name: "Soft Studio",
    summary:
      "White page, gentle book-serif headings, muted rose as the brand colour, blush alternate sections and photos toned in the brand colour (duotone) so mixed phone photos look consistent. Calm and personal. Choose for hairdressers, beauty and massage studios and small boutiques, especially when photos vary in quality.",
    bestFor: ["hairdresser", "physio", "shop"],
    fontPairs: ["lora-dm-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f6eff1",
        text: "#2a2024",
        muted: "#65575c",
        primary: "#8e4a5c",
        onPrimary: "#ffffff",
        accent: "#b0607a",
        border: "#e6d9de",
        inverse: "#3a2a30",
        onInverse: "#f5f5f5",
      },
      primaryHue: [320, 360],
      primarySaturation: [0.15, 0.45],
    },
    ranges: {
      radius: [4, 8],
      baseFontSize: [17, 18],
      scale: [1.2, 1.28],
      headingWeight: [450, 600],
      headingTracking: [-0.01, 0.01],
      headingCase: ["normal"],
      density: ["airy", "regular"],
      shadow: ["none", "subtle"],
    },
    imagery: "duotone",
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-split:image-left", "hero-image:overlay-left"],
      rhythm: "alternate",
      prefer: ["price-list:grouped", "booking:simple", "services-list:rows", "team:grid", "gallery:grid", "about:image-side"],
    },
  },
];

export function direction(id: string): Direction {
  const d = DIRECTIONS.find((x) => x.id === id);
  if (!d) throw new Error(`Unknown design direction: ${id}`);
  return d;
}
