import type { Direction } from "./design.ts";
import type { BusinessType } from "./business.ts";

/**
 * Curated design directions. Each must look clearly different from the others on the eval contact sheet
 * (typography, colour mood, light/tinted/dark page, radius, density, imagery, section rhythm).
 * Fallback colours must pass every contrast rule in design-rules.ts (packages/spec/test/directions.test.ts checks this).
 */
export const DIRECTIONS: Direction[] = [
  {
    id: "clean-swiss",
    name: "Clean Swiss",
    summary:
      "White page, tight grotesk headings, strict left-aligned grid, square corners, one saturated brand colour used sparingly. Precise and calm. Choose for accountants, clinics and installers who want to look orderly and exact.",
    bestFor: ["accountant", "dental", "physio", "builder"],
    fontPairs: ["inter-tight-inter"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f1f4f8",
        text: "#111418",
        muted: "#4a5360",
        primary: "#1d4ed8",
        onPrimary: "#ffffff",
        accent: "#2563eb",
        border: "#d5dbe3",
        inverse: "#111418",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.45, 0.95],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [16, 17],
      scale: [1.2, 1.3],
      headingWeight: [600, 750],
      headingTracking: [-0.02, -0.005],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    layout: {
      header: "bar",
      footer: "columns",
      heroes: ["hero-split:image-right", "hero-type:with-facts"],
      rhythm: "flat",
      prefer: ["services-list:rows", "price-list:table", "faq:accordion", "opening-hours:table", "contact:split-map"],
    },
  },
  {
    id: "warm-craft",
    name: "Warm Craft",
    summary:
      "White page with a soft, characterful serif (Fraunces) in headings, terracotta or brand colour for buttons, photos set on an offset colour block, cool pale sage alternate sections. Warm and hand-made without cream backgrounds. Choose for bakeries, gostilne, family restaurants and small food shops with good product photos.",
    bestFor: ["bakery", "restaurant", "shop", "tourist-farm"],
    fontPairs: ["fraunces-source-sans", "bitter-nunito-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#edf2ef",
        text: "#221b17",
        muted: "#5b504a",
        primary: "#b4441f",
        onPrimary: "#ffffff",
        accent: "#c65a2e",
        border: "#d9e0dc",
        inverse: "#2b211c",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.4, 0.85],
    },
    ranges: {
      radius: [4, 8],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [550, 700],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none", "subtle"],
    },
    imagery: "offset-block",
    layout: {
      header: "split-cta",
      footer: "columns",
      heroes: ["hero-split:image-left", "hero-image:overlay-bottom"],
      rhythm: "alternate",
      prefer: ["menu:classic", "products:grid", "image-text:image-left", "opening-hours:compact", "gallery:mosaic", "about:image-side"],
    },
  },
  {
    id: "dark-elegant",
    name: "Dark Elegant",
    summary:
      "Near-black warm page, light high-contrast Garamond headings with generous spacing, brass accents, photos in thin frames, airy sections. Evening mood. Choose for restaurants, wine bars and upscale salons with atmospheric interior or food photos; avoid when photos are dark or few.",
    bestFor: ["restaurant", "hairdresser"],
    fontPairs: ["garamond-karla"],
    palette: {
      background: "dark",
      fallback: {
        background: "#14110f",
        surface: "#1f1a17",
        text: "#f2ece5",
        muted: "#b9ada1",
        primary: "#c9a46a",
        onPrimary: "#14110f",
        accent: "#c9a46a",
        border: "#3a322b",
        inverse: "#3a1d25",
        onInverse: "#f2ece5",
      },
      primaryHue: [25, 50],
      primarySaturation: [0.3, 0.6],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [17, 18],
      scale: [1.28, 1.36],
      headingWeight: [500, 600],
      headingTracking: [-0.01, 0.01],
      headingCase: ["normal"],
      density: ["airy"],
      shadow: ["none"],
    },
    imagery: "framed",
    layout: {
      header: "stacked",
      footer: "compact",
      heroes: ["hero-image:overlay-left", "hero-type:large"],
      rhythm: "alternate",
      prefer: ["menu:two-column", "image-text:image-right", "gallery:grid", "booking:with-hours", "about:image-side", "contact:stacked"],
    },
  },
  {
    id: "bold-local",
    name: "Bold Local",
    summary:
      "White page with heavy, compact Archivo headings (uppercase allowed), square corners, a loud signal colour for buttons and full-width near-black bands for key facts. Direct and practical, built for the phone number. Choose for car repair, tyre shops, builders and trades that sell reliability and speed.",
    bestFor: ["car-repair", "builder", "shop"],
    fontPairs: ["archivo-archivo"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#eef0f3",
        text: "#0e0f12",
        muted: "#474c55",
        primary: "#c8261b",
        onPrimary: "#ffffff",
        accent: "#e0301e",
        border: "#d3d7dd",
        inverse: "#111317",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.6, 1],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [16, 17],
      scale: [1.25, 1.333],
      headingWeight: [700, 850],
      headingTracking: [-0.02, 0.01],
      headingCase: ["uppercase", "normal"],
      density: ["compact", "regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    layout: {
      header: "split-cta",
      footer: "columns",
      heroes: ["hero-type:with-facts", "hero-split:image-right"],
      rhythm: "inverse-accents",
      prefer: ["contact-strip:bar", "services-cards:compact", "cta:band", "service-area:inline", "steps:horizontal", "price-list:table"],
    },
  },
  {
    id: "clinical-calm",
    name: "Clinical Calm",
    summary:
      "Pale cool-blue page with white cards, friendly geometric sans headings, softly rounded corners and photos, lots of air. Reassuring and clean without looking sterile. Choose for dental and physio practices and other health services where trust and easy booking matter.",
    bestFor: ["dental", "physio", "accountant"],
    fontPairs: ["manrope-public-sans", "inter-tight-inter"],
    palette: {
      background: "tint",
      fallback: {
        background: "#f1f6fb",
        surface: "#ffffff",
        text: "#102230",
        muted: "#4a5d6b",
        primary: "#0e6a88",
        onPrimary: "#ffffff",
        accent: "#1479a0",
        border: "#d3e0ea",
        inverse: "#0c2331",
        onInverse: "#f5f5f5",
      },
      primaryHue: [175, 225],
      primarySaturation: [0.35, 0.85],
    },
    ranges: {
      radius: [8, 12],
      baseFontSize: [17, 18],
      scale: [1.2, 1.25],
      headingWeight: [600, 750],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["airy", "regular"],
      shadow: ["subtle", "none"],
    },
    imagery: "rounded",
    layout: {
      header: "bar",
      footer: "columns",
      heroes: ["hero-split:image-right", "hero-type:with-facts"],
      rhythm: "alternate",
      prefer: ["booking:with-hours", "services-list:two-column", "team:grid", "faq:accordion", "opening-hours:table", "steps:vertical"],
    },
  },
  {
    id: "alpine-nature",
    name: "Alpine Nature",
    summary:
      "Pale green-tinted page, sturdy slab-serif headings, forest-green buttons, photos running edge to edge on phones. Outdoorsy and honest. Choose for tourist farms, mountain huts, gostilne in the countryside and anything sold on landscape, rooms and home-grown food.",
    bestFor: ["tourist-farm", "restaurant", "bakery"],
    fontPairs: ["bitter-nunito-sans", "fraunces-source-sans"],
    palette: {
      background: "tint",
      fallback: {
        background: "#eef5ef",
        surface: "#ffffff",
        text: "#13261a",
        muted: "#44574a",
        primary: "#2d6a3a",
        onPrimary: "#ffffff",
        accent: "#3a8049",
        border: "#cfdcd2",
        inverse: "#12241a",
        onInverse: "#f5f5f5",
      },
      primaryHue: [80, 170],
      primarySaturation: [0.25, 0.7],
    },
    ranges: {
      radius: [2, 6],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [600, 750],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "full-bleed",
    layout: {
      header: "bar",
      footer: "columns",
      heroes: ["hero-image:overlay-bottom", "hero-split:image-left"],
      rhythm: "alternate",
      prefer: ["rooms:cards", "gallery:mosaic", "image-text:image-left", "opening-hours:compact", "contact:split-map", "highlights:columns"],
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    summary:
      "White page led by large, light serif headlines like a quality newspaper, restrained sans body text, square framed photos, generous whitespace and one deep ink-red colour. Typography does the work. Choose for accountants, advisers and practices with few photos, or any client whose text is stronger than their pictures.",
    bestFor: ["accountant", "physio", "dental"],
    fontPairs: ["newsreader-libre-franklin", "garamond-karla"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f2f3f5",
        text: "#16161a",
        muted: "#55555f",
        primary: "#8f1d24",
        onPrimary: "#ffffff",
        accent: "#c23a3a",
        border: "#d9d9de",
        inverse: "#16161a",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.3, 0.8],
    },
    ranges: {
      radius: [0, 0],
      baseFontSize: [18, 19],
      scale: [1.333, 1.414],
      headingWeight: [400, 500],
      headingTracking: [-0.02, 0],
      headingCase: ["normal"],
      density: ["airy"],
      shadow: ["none"],
    },
    imagery: "framed",
    layout: {
      header: "stacked",
      footer: "columns",
      heroes: ["hero-type:large", "page-header:plain"],
      rhythm: "flat",
      prefer: ["text:two-column", "highlights:list", "services-list:rows", "faq:list", "team:list", "about:text-only"],
    },
  },
  {
    id: "playful-modern",
    name: "Playful Modern",
    summary:
      "White page with chunky, quirky grotesk headings, bright berry colour, pale lilac bands, the most rounded corners allowed and arch-topped photos. Friendly and current. Choose for bakeries, hairdressers, gift and concept shops aimed at a younger local crowd.",
    bestFor: ["bakery", "hairdresser", "shop"],
    fontPairs: ["bricolage-figtree"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f1edfc",
        text: "#1c1427",
        muted: "#554d66",
        primary: "#b01f5c",
        onPrimary: "#ffffff",
        accent: "#d93f7d",
        border: "#dcd5ee",
        inverse: "#2a1236",
        onInverse: "#f5f5f5",
      },
      primaryHue: null,
      primarySaturation: [0.55, 1],
    },
    ranges: {
      radius: [10, 12],
      baseFontSize: [16, 17],
      scale: [1.25, 1.333],
      headingWeight: [700, 800],
      headingTracking: [-0.02, -0.005],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none", "subtle"],
    },
    imagery: "arched",
    layout: {
      header: "split-cta",
      footer: "compact",
      heroes: ["hero-split:image-right", "hero-type:large"],
      rhythm: "alternate",
      prefer: ["products:grid", "services-cards:grid", "price-list:grouped", "announcement:card", "gallery:grid", "team:grid"],
    },
  },
  {
    id: "industrial",
    name: "Industrial",
    summary:
      "Dark graphite page, technical grotesk headings, safety-yellow buttons and rules, black-and-white photos, square corners and dense spacing. Tough and no-nonsense. Choose for builders, installers, electricians, workshops and car repair with work-site photos.",
    bestFor: ["builder", "car-repair"],
    fontPairs: ["space-grotesk-plex", "archivo-archivo"],
    palette: {
      background: "dark",
      fallback: {
        background: "#15171a",
        surface: "#1e2125",
        text: "#eef0f2",
        muted: "#a7adb4",
        primary: "#f2c200",
        onPrimary: "#15171a",
        accent: "#f2c200",
        border: "#363a40",
        inverse: "#2b2f35",
        onInverse: "#f5f5f5",
      },
      primaryHue: [40, 55],
      primarySaturation: [0.8, 1],
    },
    ranges: {
      radius: [0, 2],
      baseFontSize: [16, 17],
      scale: [1.2, 1.28],
      headingWeight: [600, 700],
      headingTracking: [-0.02, 0.02],
      headingCase: ["normal", "uppercase"],
      density: ["compact"],
      shadow: ["none"],
    },
    imagery: "monochrome",
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-image:overlay-bottom", "hero-type:with-facts"],
      rhythm: "inverse-accents",
      prefer: ["services-list:two-column", "steps:horizontal", "service-area:list", "gallery:mosaic", "contact-strip:cards", "cta:split"],
    },
  },
  {
    id: "soft-studio",
    name: "Soft Studio",
    summary:
      "White page, gentle book-serif headings, muted rose as the brand colour, blush alternate sections and photos toned in the brand colour (duotone) so mixed phone photos look consistent. Calm and personal. Choose for hairdressers, beauty and massage studios and small boutiques, especially when photos vary in quality.",
    bestFor: ["hairdresser", "physio", "shop"],
    fontPairs: ["lora-dm-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f6eff1",
        text: "#2a2024",
        muted: "#65575c",
        primary: "#8e4a5c",
        onPrimary: "#ffffff",
        accent: "#b0607a",
        border: "#e6d9de",
        inverse: "#3a2a30",
        onInverse: "#f5f5f5",
      },
      primaryHue: [320, 360],
      primarySaturation: [0.15, 0.45],
    },
    ranges: {
      radius: [4, 8],
      baseFontSize: [17, 18],
      scale: [1.2, 1.28],
      headingWeight: [450, 600],
      headingTracking: [-0.01, 0.01],
      headingCase: ["normal"],
      density: ["airy", "regular"],
      shadow: ["none", "subtle"],
    },
    imagery: "duotone",
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-split:image-left", "hero-image:overlay-left"],
      rhythm: "alternate",
      prefer: ["price-list:grouped", "booking:simple", "services-list:rows", "team:grid", "gallery:grid", "about:image-side"],
    },
  },
  // ---------- Trade templates (docs/design/templates, owner's decision sb-landing-directions = start-three) ----------
  {
    id: "tablica",
    name: "Tablica (number plate)",
    summary:
      "Trades that live on the phone: asphalt and signal yellow, heavy uppercase Archivo, the workshop photo full-bleed under a flat dark overlay, the phone number drawn as a Slovenian registration plate with the town's code, prices as plates and a tyre tread between sections. Choose for car repair, tyre shops, towing and any trade whose customers call; works with or without photos.",
    bestFor: ["car-repair", "builder"],
    fontPairs: ["archivo-public-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#eef0f3",
        text: "#15181c",
        muted: "#4a525c",
        primary: "#15181c",
        onPrimary: "#ffffff",
        accent: "#b38f00",
        border: "#d9dee4",
        inverse: "#15181c",
        onInverse: "#f5f5f5",
        band: "#ffcc00",
        onBand: "#15181c",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [4, 6],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [850, 900],
      headingTracking: [-0.03, -0.01],
      headingCase: ["uppercase"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "M",
      motif: "plate",
      display: [40, 100],
      h2: [36, 84],
      firstFor: ["car-repair"],
      minPhotos: 0,
      // The hero's eyebrow and fact label are set in the band colour on the photo's dark overlay (motifs.css).
      textPairs: [["band", "inverse"]],
      homepage: [
        "hero-signature:photo tone inverse: fact phone, the best workshop photo (none: leave image out); factLabel how the client wants to be reached; the hero adds address and hours itself",
        "services-list:two-column: every service the client lists, a short name and one plain line each",
        "price-list:tags tone inverse: only the prices the client gave, one group without a name; footnote only if the client said how the rest is priced",
        "image-text:image-left: a second photo with one thing the client stressed (tyres, towing, the family business)",
        "contact:call-out tone band: the closing call; the title says to call",
      ],
    },
    layout: {
      headerTone: "inverse",
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:photo"],
      rhythm: "inverse-accents",
      prefer: ["services-list:two-column", "price-list:tags", "image-text:image-left", "contact:call-out"],
    },
  },
  {
    id: "cevi",
    name: "Cevi (pipes)",
    summary:
      "Field trades with no photos: white page, tight Space Grotesk, a radiator drawn in code fed by a red hot pipe and a blue cold pipe, the phone number in a red block, the two pipes running on as dividers, a step line with valves and a service-area line with stops. Choose for installers, plumbers and heating trades, especially without photos.",
    bestFor: ["builder"],
    fontPairs: ["space-grotesk-public-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#e6ebf0",
        text: "#101820",
        muted: "#465361",
        primary: "#d63c22",
        onPrimary: "#ffffff",
        accent: "#1f6fe0",
        border: "#d3dae1",
        inverse: "#101820",
        onInverse: "#f5f5f5",
        band: "#1f6fe0",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [8, 10],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [700, 700],
      headingTracking: [-0.04, -0.02],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "S",
      motif: "pipes",
      display: [40, 96],
      h2: [34, 72],
      firstFor: ["builder"],
      minPhotos: 0,
      homepage: [
        "hero-signature:drawing: fact phone; factLabel what the call is for (e.g. a free site visit); factNote the client's call-back promise if there is one; no image",
        "services-list:rows: every service the client lists, a short name and one plain line each",
        "text:narrow tone band: one statement the client made that matters for the decision (a subsidy, a guarantee) as the heading, one short paragraph",
        "steps:horizontal tone alt: how a job goes, from the client's own words (call, visit, written offer)",
        "service-area:list: where the client works (the places come from the business facts)",
        "contact:call-out tone inverse: the closing call; the title in the client's voice",
      ],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:drawing"],
      rhythm: "inverse-accents",
      prefer: ["services-list:rows", "steps:horizontal", "service-area:list", "contact:call-out"],
    },
  },
  {
    id: "skorja",
    name: "Skorja (crust)",
    summary:
      "Food makers: a dark roast hero with the product photo in a tall oven arch and the opening time on a round wheat seal, a fat Bitter slab serif, prices on a ruled board with dotted leaders, a wheat band for the weekly special and the loaf's three scoring cuts as section mark. Choose for bakeries, pastry shops, butchers and coffee roasters with at least one good product photo.",
    bestFor: ["bakery", "shop"],
    fontPairs: ["bitter-karla"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#eef1f0",
        text: "#24130a",
        muted: "#5c4636",
        primary: "#8a4a1c",
        onPrimary: "#ffffff",
        accent: "#a0561f",
        border: "#e2d3c5",
        inverse: "#24130a",
        onInverse: "#f5f5f5",
        band: "#f4b942",
        onBand: "#24130a",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [8, 12],
      baseFontSize: [18, 19],
      scale: [1.25, 1.333],
      headingWeight: [850, 900],
      headingTracking: [-0.03, -0.01],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "rounded",
    template: {
      id: "J",
      motif: "crust",
      display: [40, 84],
      h2: [34, 64],
      firstFor: ["bakery"],
      minPhotos: 1,
      // The hero's eyebrow is set in the band colour on the arch hero's inverse ground (motifs.css).
      textPairs: [["band", "inverse"]],
      homepage: [
        "hero-signature:arch tone inverse: fact opening (phone when the client gave no hours), the best product photo; primary a link to the offer section, secondary a call or order link",
        "price-list:grouped: what is on the shelf every day, one group without a name, prices only as the client gave them (placeholders for the rest)",
        "cta:band tone band: the weekly or seasonal special the client named, with one order button",
        "image-text:image-left tone inverse: how the client makes it, with the second photo",
        "about:text-only: the owner's own sentence about who works there, as the heading, and one short paragraph",
        "contact:call-out: orders and visits; the title names what to call for",
      ],
    },
    layout: {
      headerTone: "inverse",
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:arch"],
      rhythm: "alternate",
      prefer: ["price-list:grouped", "cta:band", "image-text:image-left", "about:text-only", "contact:call-out"],
    },
  },
  {
    id: "racun",
    name: "Račun (receipt)",
    summary:
      "Offices with no photos at all: one plain grotesk (IBM Plex Sans) with tabular figures, ledger green on white, a solid green field holding a tilted paper receipt that lists what the office does (check marks, a torn edge, a double-ruled total), the client types and the founding year set wall-sized, services as ledger rows on mint. Choose for accountants, lawyers, notaries, insurance and translators, especially without photos.",
    bestFor: ["accountant"],
    fontPairs: ["ibm-plex-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#e4f1ea",
        text: "#0c2a1e",
        muted: "#3f574b",
        primary: "#0b5a3c",
        onPrimary: "#ffffff",
        accent: "#2e8a5f",
        border: "#cfe0d6",
        inverse: "#0c2a1e",
        onInverse: "#f2f7f4",
        band: "#0b5a3c",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [4, 4],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [700, 700],
      headingTracking: [-0.04, -0.03],
      headingCase: ["normal"],
      density: ["regular"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "R",
      motif: "ledger",
      display: [40, 80],
      h2: [34, 72],
      firstFor: ["accountant"],
      minPhotos: 0,
      homepage: [
        "hero-signature:receipt: fact phone; factLabel the call button's label (e.g. \"Pokličite nas\"); receipt.title what the office does for its clients, receipt.lines four to six of the client's services in a few words each, receipt.total only from the client's words about prices (e.g. Cena / po dogovoru), factNote the client's one sentence on what the price depends on; secondary an e-mail link; no eyebrow (the hero shows the address itself); no image",
        "highlights:figures: who the client works for, each as one short word or abbreviation from the client's text (s.p., d.o.o., društva) with a plain label under it; heading a short label (e.g. Za koga delamo)",
        "services-list:rows tone alt: every service the client lists, a short name and one plain line each; intro how clients bring their documents, if the client said so",
        "about:figure: figure the year the business started (label e.g. Delamo od leta), only if the client gave it; heading where the office works; ownerName and ownerRole the person the client named; one short paragraph about who else works there",
        "contact:call-out tone inverse: the closing call; the title says how the client wants to be reached (e.g. announce a visit by phone)",
      ],
      textPairs: [
        ["primary", "background"],
        ["primary", "surface"],
      ],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:receipt"],
      rhythm: "alternate",
      prefer: ["highlights:figures", "services-list:rows", "about:figure", "contact:call-out"],
    },
  },
  {
    id: "etiketa",
    name: "Etiketa (bottle label)",
    summary:
      "Shops that sell things you can hold: olive green and terracotta, a bookish serif (Lora), everything set like a bottle label. The headline sits in a white label card with a double inner rule and an olive branch drawn in code, the shop photo in a tall stone-doorway arch with a round detail photo over its edge, each priced product on its own label, a terracotta band for gift boxes, the shop front in an arch beside the hours. Choose for delis, wine, honey and farm shops and gift shops with at least one photo.",
    bestFor: ["shop"],
    fontPairs: ["lora-karla"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#e3ebd3",
        text: "#23281a",
        muted: "#4d5440",
        primary: "#b9492f",
        onPrimary: "#ffffff",
        accent: "#869850",
        border: "#cfd6bb",
        inverse: "#3b4819",
        onInverse: "#f5f5f5",
        band: "#b9492f",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [6, 6],
      baseFontSize: [17, 18],
      scale: [1.2, 1.25],
      headingWeight: [700, 700],
      headingTracking: [-0.03, -0.02],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "T",
      motif: "label",
      display: [36, 72],
      h2: [34, 72],
      firstFor: ["shop"],
      minPhotos: 1,
      homepage: [
        "hero-signature:label tone inverse: fact address (no factLabel); image the best photo of the shop or its shelves, inset a close detail (a product); primary a link to the gift or offer section, secondary a link to the products",
        "price-list:tags: two to four products the client priced, each on its own label: name, note the quantity or size as the client gave it (0,5 l, 1 kg), the price; one group without a name; intro the client's sentence on where the products come from",
        "text:narrow: the rest of the range in one sentence as the paragraph, in the client's words; the heading a short label (e.g. Imamo tudi)",
        "image-text:round tone band: the gift boxes or the seasonal offer the client named, with its photo; link the way to order (a call)",
        "opening-hours:photo tone alt: image the shop front, inset another detail; note hours the client gave for a season, if any",
        "contact:call-out tone inverse: orders and visits; the title names what to call for",
      ],
      textPairs: [
        ["primary", "background"],
        ["inverse", "background"],
      ],
    },
    layout: {
      headerTone: "inverse",
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:label"],
      rhythm: "alternate",
      prefer: ["price-list:tags", "text:narrow", "image-text:round", "opening-hours:photo", "contact:call-out"],
    },
  },
  {
    id: "jedilnik",
    name: "Jedilnik (menu card)",
    summary:
      "Inns and restaurants as a printed menu: bottle green and brass, a classic serif (EB Garamond) over a friendly sans, the photo of the house full-bleed with a white menu card laid over it and hanging into the next section, the daily offers on a green band with prices at headline size, dishes as round plates, the seat count as a giant brass numeral beside overlapping photos, and a brass spoon from the name as brand mark and divider. Choose for gostilne, restaurants, wine cellars and guest houses with a photo of the house and of the dishes.",
    bestFor: ["restaurant"],
    fontPairs: ["garamond-figtree"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#edf3ef",
        text: "#1b241f",
        muted: "#4d5a52",
        primary: "#16382b",
        onPrimary: "#ffffff",
        accent: "#a8862f",
        border: "#d6ddd7",
        inverse: "#16382b",
        onInverse: "#f2f5f3",
        band: "#d2ab55",
        onBand: "#0f2a20",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [4, 4],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [600, 600],
      headingTracking: [-0.03, -0.015],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "K",
      motif: "spoon",
      display: [40, 72],
      h2: [34, 80],
      firstFor: ["restaurant"],
      minPhotos: 1,
      homepage: [
        "hero-signature:card: fact address (no factLabel); image the photo of the house or its terrace; primary a reservation call (\"Rezervirajte mizo\"), secondary a link to the menu",
        "price-list:offers tone inverse: the standing offers the client priced (a daily lunch, a Sunday menu), one group each: the group name says when, the item is the offer with what it includes as its note; title for screen readers (e.g. Malica in nedeljsko kosilo)",
        "products:plates: three dishes the client priced, each with its top-down photo; then the dishes the client named without a price (a price placeholder each); intro the client's sentence on where the food comes from",
        "image-text:pair tone inverse: the terrace or the room for groups: image and inset two photos of it, figure the seat count the client gave, the heading reads on from it; link a reservation call",
        "team:photo: the family or the people the client named, each with their role; image a photo of the kitchen or the people at work",
        "contact:call-out tone inverse: reservations; the title names what to call for",
      ],
      textPairs: [
        ["band", "inverse"],
        ["primary", "background"],
      ],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:card"],
      rhythm: "inverse-accents",
      prefer: ["price-list:offers", "products:plates", "image-text:pair", "team:photo", "contact:call-out"],
    },
  },
  {
    id: "ogledalo",
    name: "Ogledalo (mirror)",
    summary:
      "Salons with good photos: wine and blush from a salon's own palette, a tight grotesk (Inter Tight) set very large, the salon's name wall-sized in blush behind the hero, three photos in mirror arches of different heights, a wine band with the booking sentence, the price list set like a masthead beside a giant title, the team on blush with an arched photo of the salon. Choose for hairdressers, beauty and nail studios, barbers and tailors with at least three photos.",
    bestFor: ["hairdresser"],
    fontPairs: ["inter-tight-dm-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#f6e3e7",
        text: "#2b1418",
        muted: "#5e4449",
        primary: "#7a2e3a",
        onPrimary: "#ffffff",
        accent: "#b0607a",
        border: "#e6d3d7",
        inverse: "#2b1418",
        onInverse: "#f5eef0",
        band: "#7a2e3a",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [6, 6],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [800, 800],
      headingTracking: [-0.04, -0.03],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "L",
      motif: "mirror",
      display: [44, 96],
      h2: [34, 72],
      firstFor: ["hairdresser"],
      minPhotos: 3,
      homepage: [
        "hero-signature:mirrors: fact phone; factLabel the call button's label (e.g. \"Naročite se\"); wordmark one word of the business name; images three photos of the work and the people (portrait-friendly); secondary a link to the price list",
        "cta:band tone band: the client's own sentence about booking as the heading; primary a call",
        "price-list:grouped: the prices the client gave, one group without a name; services named without a price get a price placeholder; title short (e.g. Cenik); intro one thing the client stressed about the work",
        "team:photo tone alt: the people the client named with their roles; image a photo of the salon, inset a detail (products, tools)",
        "contact:call-out: visits and booking; the title names how to book",
      ],
      textPairs: [
        ["primary", "background"],
        ["primary", "surface"],
      ],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:mirrors"],
      rhythm: "alternate",
      prefer: ["cta:band", "price-list:grouped", "team:photo", "contact:call-out"],
    },
  },
  {
    id: "nasmeh",
    name: "Nasmeh (smile)",
    summary:
      "Health practices, calm on purpose: white and mint with a deep teal-green, one friendly grotesk (Figtree), the practice's reassuring promise as the headline, the photo round on a mint disc with a coral smile arc under it and a short note on a tilted chip, the opening hours drawn as a week chart, services as a ruled list with arc bullets beside a note on how the practice charges, the team with a round and an arched photo, a teal closing call. Choose for dentists, doctors, vets, opticians and pharmacies with at least one photo.",
    bestFor: ["dental"],
    fontPairs: ["figtree-figtree"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#dff4ee",
        text: "#0f2f38",
        muted: "#44606a",
        primary: "#0c7a70",
        onPrimary: "#ffffff",
        accent: "#e4573f",
        border: "#cfe3de",
        inverse: "#0f2f38",
        onInverse: "#ecf3f1",
        band: "#0c7a70",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [10, 12],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [800, 800],
      headingTracking: [-0.04, -0.03],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "O",
      motif: "smile",
      display: [40, 76],
      h2: [34, 72],
      firstFor: ["dental"],
      minPhotos: 1,
      homepage: [
        "hero-signature:disc: fact phone; factLabel the call button's label (e.g. \"Naročite se\"); headline the client's most reassuring promise in their words; factNote one short fact for the chip (e.g. who they accept); image a photo of the practitioner or the room; secondary an e-mail link",
        "opening-hours:week tone alt: the heading names the hours; note how to book, from the client's words",
        "services-list:aside: every service the client lists, by name (a description only where the client said more); note how the client charges (self-paying, prices after the exam), in their words",
        "team:photo: the people the client named with their roles; image the practitioner, inset the waiting room or the surgery",
        "contact:call-out tone band: booking; the title says how to book",
      ],
      textPairs: [
        ["primary", "background"],
        ["primary", "surface"],
      ],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:disc"],
      rhythm: "alternate",
      prefer: ["opening-hours:week", "services-list:aside", "team:photo", "contact:call-out"],
    },
  },
  {
    id: "markacija",
    name: "Markacija (trail blaze)",
    summary:
      "Places sold on the view: the landscape fills the first screen under a flat dark overlay with the headline at the bottom left, the places reached from the house on red trail signs on a wooden post, a mountain ridge cutting into every dark section, the Slovenian trail blaze (a red ring, a white centre) as the brand mark and bullet. A heavy serif (Fraunces) on white, meadow green and forest green, signal red for buttons and the weekend band; prices at headline size, five photos edge to edge. Choose for tourist farms, mountain huts, guesthouses and campsites with many photos.",
    bestFor: ["tourist-farm"],
    fontPairs: ["fraunces-nunito-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#eaf3e4",
        text: "#17241b",
        muted: "#48584c",
        primary: "#c8202a",
        onPrimary: "#ffffff",
        accent: "#5a9468",
        border: "#d5e0d2",
        inverse: "#1d3a2a",
        onInverse: "#f2f6f0",
        band: "#c8202a",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [6, 8],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [900, 900],
      headingTracking: [-0.035, -0.025],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "full-bleed",
    template: {
      id: "N",
      motif: "trail",
      display: [44, 112],
      h2: [34, 80],
      firstFor: ["tourist-farm"],
      minPhotos: 5,
      homepage: [
        "hero-signature:view: fact phone; factLabel the call button's label (e.g. \"Rezervirajte\"); headline what the view gives the guest, in the client's words; eyebrow where the place is (the valley, the region); image the widest landscape photo; signs up to three places the client said the paths lead to, a note only with a time or distance the client gave; secondary a link to the rooms page",
        "price-list:rates: the room prices the client gave (per night, half board) with their units; title what the rooms are; intro what every room has; image a photo of a room; footnote a free stay or discount the client mentioned",
        "gallery:wall: five photos of the place, the animals and the food (not the hero's); the title names them for screen readers",
        "image-text:image-right tone alt: eyebrow the subject (\"Zajtrk\"); heading what the farm makes, in the client's words; image the food or the produce",
        "opening-hours:poster tone band: eyebrow what is open (\"Izletniška kmetija\"); title when and what (\"Ob sobotah in nedeljah kuhamo kosila\"); note the dishes and the group arrangement, in the client's words",
        "services-list:aside: the trails and destinations the client named (a description only with what the client said, a season or a distance); note how to get there (the road, the last stretch), in the client's words",
        "team:list tone inverse: the hosts the client named with their roles; the heading how long they have farmed",
        "contact:call-out tone inverse: bookings; the title says how to book",
      ],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:view"],
      rhythm: "alternate",
      prefer: ["price-list:rates", "gallery:wall", "opening-hours:poster", "services-list:aside", "contact:call-out"],
    },
  },
  {
    id: "pregib",
    name: "Pregib (bend)",
    summary:
      "One-person practices that sell appointments: the logo's bent line drawn as a wide pale limb behind the headline with a joint in orange, the photo with one cut corner hanging into a dark band of large orange figures, complaints as cut-corner tiles, the methods as one large sentence, prices on cut-corner cards, a teal booking band, three contact columns. A bold grotesk (Bricolage Grotesque) with Public Sans, teal, deep green-black, mist and orange buttons with dark text; the phone bar books first. Choose for physiotherapists, massage therapists, trainers and other practices booked online.",
    bestFor: ["physio"],
    fontPairs: ["bricolage-public-sans"],
    palette: {
      background: "white",
      fallback: {
        background: "#ffffff",
        surface: "#e6f2f0",
        text: "#10302d",
        muted: "#44605c",
        primary: "#0f6b63",
        onPrimary: "#ffffff",
        accent: "#de7b2d",
        border: "#cfe0dd",
        inverse: "#10302d",
        onInverse: "#e6f2f0",
        band: "#0f6b63",
        onBand: "#ffffff",
      },
      primaryHue: null,
      primarySaturation: [0, 1],
    },
    ranges: {
      radius: [6, 8],
      baseFontSize: [17, 18],
      scale: [1.25, 1.333],
      headingWeight: [800, 800],
      headingTracking: [-0.04, -0.03],
      headingCase: ["normal"],
      density: ["regular", "airy"],
      shadow: ["none"],
    },
    imagery: "natural",
    template: {
      id: "P",
      motif: "bend",
      display: [44, 88],
      h2: [36, 72],
      firstFor: ["physio"],
      minPhotos: 0,
      homepage: [
        "hero-signature:bend: fact address; headline the client's promise about how they work, in their words; intro who they are (name, title) and one practical fact (no referral needed); image the practice room; primary the booking link (when the client books online, else the call); secondary the call",
        "highlights:figures tone inverse: three or four figures the client gave (years of experience, years in practice, session length, hours), each title the figure as written (\"12 let\") and its text what it counts",
        "services-list:aside: what people come with, by name only; heading who comes; note how the client charges (self-paying, no referral), in their words",
        "text:narrow: eyebrow how they work (\"Kako delam\"); one paragraph naming the methods the client uses",
        "price-list:tags tone alt: every price the client gave, the duration or condition as the note",
        "cta:band tone band: how to book; primary the booking link, secondary the call",
        "contact-strip:cards: where, when and how to reach them",
      ],
      textPairs: [["accent", "inverse"]],
      phoneBar: ["booking", "call", "directions"],
    },
    layout: {
      header: "bar",
      footer: "compact",
      heroes: ["hero-signature:bend"],
      rhythm: "alternate",
      prefer: ["highlights:figures", "services-list:aside", "price-list:tags", "cta:band", "contact-strip:cards"],
    },
  },
];

/** The template direction that is the first choice for a business type, if the photos allow it. */
export function templateFor(businessType: BusinessType, photoCount: number): Direction | undefined {
  return DIRECTIONS.find((d) => d.template && d.template.firstFor.includes(businessType) && photoCount >= d.template.minPhotos);
}

export function direction(id: string): Direction {
  const d = DIRECTIONS.find((x) => x.id === id);
  if (!d) throw new Error(`Unknown design direction: ${id}`);
  return d;
}
