/**
 * Throwaway-inbox domains refused at sign-in (one free tier per real inbox). Subdomains of these are
 * refused too. This is a hand-kept list of the well-known services and their alternate domains; the
 * community list at github.com/disposable-email-domains/disposable-email-domains (CC0, ~4,000 entries)
 * can replace it wholesale. Add a domain here when it shows up in sign-ups.
 */
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  // Mailinator and its alternate domains
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "notmailinator.com",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "devnullmail.com",
  "letthemeatspam.com",
  "mailinater.com",
  "reallymymail.com",
  "safetymail.info",
  "sogetthis.com",
  "spamhereplease.com",
  "streetwisemail.com",
  "suremail.info",
  "thisisnotmyrealemail.com",
  "tradermail.info",
  "veryrealemail.com",
  "zippymail.info",
  // Guerrilla Mail
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "pokemail.net",
  "spam4.me",
  // 10 Minute Mail and similar timers
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.co.uk",
  "10minemail.com",
  "20minutemail.com",
  "zehnminutenmail.de",
  // Temp Mail family
  "temp-mail.org",
  "temp-mail.io",
  "tempmail.com",
  "tempmail.net",
  "tempmail.dev",
  "tempmail.plus",
  "tempmailo.com",
  "tempmail.us.com",
  "tempmailaddress.com",
  "tempail.com",
  "tempinbox.com",
  "tempr.email",
  "tmpmail.org",
  "tmpmail.net",
  "mailto.plus",
  "fexpost.com",
  "fexbox.org",
  "mytemp.email",
  // YOPmail and its alternate domains
  "yopmail.com",
  "yopmail.net",
  "yopmail.fr",
  "cool.fr.nf",
  "jetable.fr.nf",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  // TrashMail
  "trashmail.com",
  "trashmail.net",
  "trashmail.de",
  "trashmail.me",
  "trashmail.io",
  "trash-mail.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wegwerfemail.de",
  // Fake Mail Generator domains
  "fakemailgenerator.com",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  // 1secmail
  "1secmail.com",
  "1secmail.net",
  "1secmail.org",
  // Others
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "dropmail.me",
  "emailfake.com",
  "emailondeck.com",
  "fakeinbox.com",
  "getairmail.com",
  "getnada.com",
  "nada.email",
  "harakirimail.com",
  "inboxkitten.com",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailforspam.com",
  "mailnesia.com",
  "mailnull.com",
  "mailpoof.com",
  "mailsac.com",
  "mintemail.com",
  "mohmal.com",
  "spambox.us",
  "spamfree24.org",
  "spamgourmet.com",
  "throwawaymail.com",
  "anonbox.net",
  "incognitomail.org",
  "byom.de",
  "crazymailing.com",
  "inboxbear.com",
]);
