/**
 * The stance deck (design-studio.md §5.2, inventory I8): 80 named visual languages across six families, a third of them
 * rooted in Slovene visual culture (`slovene`). Each fits at least a few trades and says what it turns into when done
 * badly: the avoid notes name the banned pattern (docs/PRODUCT.md) each language is most tempted by (monospace on the
 * paper ones, tracked capitals on the signs, cream and wood-grain grounds on the folk and rural ones, gradients and shine
 * on the metal and night ones).
 *
 * Visual only: no pitch implies a fact, a year or a heritage the client didn't give. Slovene stances are drawn as visual
 * languages (a beehive panel, the trail blaze, a Secession facade), never as copies of a particular work, brand or crest.
 * Signatures not yet in the inventory (ornament/…, texture/…, typeTreatment/…, divider/…, composition/…) name what it
 * should build; studio.test.ts keeps every stance carrying at least one asset that renders today.
 */
import type { Stance } from "./deck.ts";

const PRINT: readonly Stance[] = [
  {
    id: "workshop-docket",
    name: "Workshop docket",
    pitch: "The page reads like the job ticket you get with your car: carbon-copy blue, stamped numbers, typed lines.",
    family: "print",
    trades: { fit: ["car-repair", "builder", "shop"], never: ["dental", "hairdresser", "physio"], subNever: ["florist", "boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["space-grotesk-plex", "ibm-plex-sans", "archivo-public-sans"],
      palette: ["cool", "signal", "two-colour"],
      imagery: ["natural", "framed"],
      shape: ["square", "cut"],
      density: ["compact", "regular"],
      motion: "still",
    },
    signatures: ["fact/ticket", "fact/stamp", "mask/ticket", "typeTreatment/typed-line"],
    references: ["tablica", "racun"],
    avoid: "A form: grey boxes, every line ruled, monospace 'typed' labels, nothing large enough to read from across the street.",
    cues: { goals: ["call", "enquire"], angles: ["speed", "value"], materials: ["olje", "guma", "orodje", "cev"] },
  },
  {
    id: "seed-packet",
    name: "Seed packet",
    pitch: "A paper packet you buy at the market: one drawn object on a flat colour, the name in a curved label, small print on the back.",
    family: "print",
    trades: { fit: ["bakery", "shop", "tourist-farm"], never: ["car-repair", "accountant", "dental"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-nunito-sans", "bitter-karla", "lora-karla"],
      palette: ["earth", "warm", "muted"],
      imagery: ["natural", "rounded", "duotone"],
      shape: ["soft", "arch"],
      density: ["regular", "airy"],
      motion: "calm",
    },
    signatures: ["fact/tag", "mask/arch", "treatment/duotone", "ornament/drawn-object"],
    references: ["etiketa", "skorja"],
    avoid: "A farmhouse cliché: kraft brown everywhere, script fonts and wheat ears on every heading.",
    cues: { goals: ["visit", "order", "browse"], angles: ["craft", "speciality"], materials: ["seme", "moka", "med", "zelenjava", "sadje", "rože"] },
  },
  {
    id: "till-receipt",
    name: "Till receipt",
    pitch: "A long till receipt: one narrow column of lines, the item on the left and its price on the right, a heavy total, a torn edge at the foot of each section.",
    family: "print",
    trades: { fit: ["shop", "bakery", "restaurant", "car-repair", "hairdresser", "accountant"], never: ["dental", "physio", "tourist-farm"] },
    axes: {
      ground: ["white", "tint"],
      type: ["ibm-plex-sans", "space-grotesk-plex", "archivo-public-sans"],
      palette: ["neutral", "monochrome", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square", "cut"],
      density: ["compact"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/ticket", "mask/ticket", "divider/torn-edge", "typeTreatment/ruled-total", "composition/prices/receipt-column"],
    references: ["racun", "etiketa"],
    avoid: "A dot-matrix pastiche: monospace everywhere, grey text too small to read, prices invented to fill the column.",
    cues: { goals: ["order", "browse"], angles: ["value", "speed"], materials: ["kava", "malica", "pecivo", "storitev"] },
  },
  {
    id: "dispensary-label",
    name: "Dispensary label",
    pitch: "The printed label on a pharmacy jar: a white field inside a ruled frame, one clear name, short precise lines beneath it, a single colour for the rules.",
    family: "print",
    trades: { fit: ["dental", "physio", "hairdresser", "shop"], never: ["car-repair", "builder", "tourist-farm", "restaurant"] },
    axes: {
      ground: ["white", "tint"],
      type: ["garamond-figtree", "newsreader-libre-franklin", "ibm-plex-sans"],
      palette: ["cool", "muted", "two-colour"],
      imagery: ["framed", "natural", "rounded"],
      shape: ["square", "soft"],
      density: ["regular", "airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/tag", "mask/circle", "ornament/label-frame", "divider/double-rule"],
    references: ["nasmeh", "etiketa"],
    avoid: "A hospital form: clinical blue on everything, tiny type, a frame round every block until nothing stands out.",
    cues: { goals: ["book", "call"], angles: ["person", "speciality"], materials: ["krema", "olje", "zelišča", "čaj", "mazilo"] },
  },
  {
    id: "station-timetable",
    name: "Station timetable",
    pitch: "A printed station timetable: times in big figures in strict columns, hairline rules between the rows, one colour band marking today's line.",
    family: "print",
    trades: { fit: ["physio", "dental", "hairdresser", "bakery", "car-repair", "restaurant", "accountant"], never: [] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-inter", "archivo-public-sans", "ibm-plex-sans"],
      palette: ["signal", "neutral", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/numeral", "typeTreatment/tabular-figures", "composition/hours/timetable-board", "divider/hairline"],
    references: ["proge", "racun"],
    avoid: "A spreadsheet: every figure the same size, numbered section labels, the hours lost in a grid of zeros.",
    cues: { goals: ["book", "visit", "call"], angles: ["speed", "value"] },
  },
  {
    id: "market-broadsheet",
    name: "Market-day broadsheet",
    pitch: "A one-sheet local paper: a heavy masthead with the name, narrow columns divided by rules, one headline over a cropped photo, bold run-in subheads.",
    family: "print",
    trades: { fit: ["restaurant", "shop", "bakery", "tourist-farm", "builder", "car-repair"], never: ["dental", "physio"] },
    axes: {
      ground: ["white"],
      type: ["newsreader-libre-franklin", "bitter-karla", "garamond-figtree"],
      palette: ["neutral", "monochrome", "deep"],
      imagery: ["monochrome", "natural", "framed"],
      shape: ["square"],
      density: ["compact"],
      rhythm: ["flat", "alternate"],
      motion: "still",
    },
    signatures: ["imagery/monochrome", "typeTreatment/masthead", "divider/column-rule", "composition/opener/front-page"],
    references: ["jedilnik", "mirno"],
    avoid: "A fake newspaper: invented headlines and dates, a 'novice' badge, filler columns written to fill the shape.",
    cues: { goals: ["visit", "browse"], angles: ["place", "person"], local: true },
  },
  {
    id: "picture-postcard",
    name: "Picture postcard",
    pitch: "A postcard from the place: one photo with a white border, the town's name set large across it, a stamp-shaped frame in the corner, a short note beside it.",
    family: "print",
    trades: { fit: ["tourist-farm", "restaurant", "bakery", "shop"], never: ["accountant", "car-repair", "dental", "builder"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-source-sans", "lora-karla", "bitter-nunito-sans"],
      palette: ["bright", "warm", "cool"],
      imagery: ["framed", "full-bleed"],
      shape: ["square"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["mask/stamp", "imagery/framed", "fact/stamp", "typeTreatment/place-name-overprint"],
    references: ["markacija", "popoldan"],
    avoid: "A souvenir card: a collage of sights, a cursive 'Pozdrav iz' headline, every photo tilted at an angle.",
    cues: { goals: ["visit", "book"], angles: ["place"], local: true },
  },
  {
    id: "kitchen-index-card",
    name: "Kitchen index card",
    pitch: "A ruled index card from the kitchen drawer: the heading on the top line, the offer as a short ruled list, one drawn object in the corner, a single ink colour.",
    family: "print",
    trades: { fit: ["bakery", "restaurant", "tourist-farm", "shop"], never: ["car-repair", "accountant", "dental", "builder"], subNever: ["boutique", "florist"] },
    axes: {
      ground: ["white", "tint"],
      type: ["lora-karla", "bitter-karla", "fraunces-nunito-sans"],
      palette: ["warm", "two-colour", "muted"],
      imagery: ["rounded", "natural"],
      shape: ["soft", "square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/spoon", "divider/ruled-line", "ornament/drawn-object", "composition/list/index-card"],
    references: ["skorja", "jedilnik"],
    avoid: "Scrapbook kitsch: handwriting fonts, coffee rings, tape on every photo, a beige page.",
    cues: { goals: ["order", "visit"], angles: ["craft", "family-history"], materials: ["moka", "jajca", "maslo", "sir", "juha", "štruklji"] },
  },
  {
    id: "bottle-label",
    name: "Bottle label",
    pitch: "A wine or oil bottle label: a framed panel with a double inner rule, the name in a calm serif, a few small lines under it, plenty of plain bottle around.",
    family: "print",
    trades: { fit: ["shop", "restaurant", "tourist-farm", "bakery"], never: ["car-repair", "builder", "dental", "physio", "accountant"], subNever: ["boutique", "florist"] },
    axes: {
      ground: ["tint", "dark", "white"],
      type: ["lora-karla", "garamond-karla", "fraunces-source-sans"],
      palette: ["deep", "earth", "muted"],
      imagery: ["arched", "framed"],
      shape: ["arch", "square"],
      density: ["airy", "regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["motif/label", "mask/arch", "divider/double-rule", "ornament/label-frame"],
    references: ["etiketa", "jedilnik"],
    avoid: "A luxury cliché: black and gold, script capitals, a crest the client never had.",
    cues: { goals: ["order", "visit", "browse"], angles: ["craft", "place", "speciality"], materials: ["vino", "olje", "žganje", "kis", "sok", "med"], local: true },
  },
  {
    id: "technical-drawing",
    name: "Technical drawing",
    pitch: "An engineer's drawing sheet: thin construction lines, dimension marks along the edges, a title block in the corner holding the name, one ink colour on white.",
    family: "print",
    trades: { fit: ["builder", "car-repair"], never: ["bakery", "restaurant", "hairdresser", "tourist-farm"] },
    axes: {
      ground: ["white"],
      type: ["space-grotesk-plex", "ibm-plex-sans", "archivo-public-sans"],
      palette: ["cool", "monochrome", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square", "cut"],
      density: ["regular", "compact"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/pipes", "ornament/dimension-line", "typeTreatment/title-block", "texture/drafting-grid"],
    references: ["cevi", "tablica"],
    avoid: "Blueprint wallpaper: white lines on blue everywhere, a grid behind every block, nothing human on the page.",
    cues: { goals: ["enquire", "call"], angles: ["speciality", "craft"], materials: ["cev", "kabel", "les", "streha", "načrt", "beton"] },
  },
  {
    id: "hang-tag",
    name: "Hang tag",
    pitch: "A card hang tag on a string: a name or a price on a punched card, the cord drawn from one section down to the next, clean card-stock colours.",
    family: "print",
    trades: { fit: ["shop", "hairdresser", "bakery"], never: ["car-repair", "builder", "dental", "accountant", "physio"] },
    axes: {
      ground: ["white", "tint"],
      type: ["lora-dm-sans", "bricolage-figtree", "figtree-figtree"],
      palette: ["muted", "warm", "bright"],
      imagery: ["framed", "natural"],
      shape: ["soft", "cut"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["fact/tag", "motif/tag", "ornament/string-line"],
    references: ["etiketa", "ogledalo"],
    avoid: "A sale flyer: red 'akcija' tags everywhere, prices crossed out, discounts nobody gave.",
    cues: { goals: ["browse", "order", "visit"], angles: ["craft", "value"], materials: ["obleka", "blago", "volna", "šal", "torba", "rože"] },
  },
  {
    id: "account-ledger",
    name: "Account ledger",
    pitch: "A bound ledger page: ruled rows, figures flush right in a firm column, a double rule under the total, one red rule for the line that matters.",
    family: "print",
    trades: { fit: ["accountant", "shop", "builder"], never: ["hairdresser", "bakery", "tourist-farm", "restaurant"], subNever: ["florist"] },
    axes: {
      ground: ["white"],
      type: ["ibm-plex-sans", "newsreader-libre-franklin", "garamond-figtree"],
      palette: ["neutral", "deep", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/ledger", "fact/numeral", "divider/double-rule", "typeTreatment/tabular-figures"],
    references: ["racun"],
    avoid: "An accounting app: dashboards, charts, green arrows, a grid of stat cards with numbers nobody gave.",
    cues: { goals: ["enquire", "call", "book"], angles: ["speed", "value", "person"], materials: ["davek", "račun", "plača", "bilanca", "knjigovodstvo"] },
  },
  {
    id: "herbarium-sheet",
    name: "Herbarium sheet",
    pitch: "A herbarium sheet: one specimen photographed flat on white, a small ruled label in the lower corner, the rest of the sheet left empty on purpose.",
    family: "print",
    trades: { fit: ["shop", "tourist-farm", "restaurant", "bakery"], never: ["car-repair", "builder", "accountant", "dental"], subNever: ["boutique"] },
    axes: {
      ground: ["white"],
      type: ["garamond-karla", "lora-karla", "newsreader-libre-franklin"],
      palette: ["muted", "earth", "neutral"],
      imagery: ["natural", "framed"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/stem", "fact/tag", "imagery/natural", "ornament/specimen-label"],
    references: ["etiketa", "mirno"],
    avoid: "A botanical print shop: vintage plates on every block, a sepia page, Latin names that aren't the client's.",
    cues: { goals: ["visit", "browse", "order"], angles: ["craft", "place"], materials: ["rože", "zelišča", "čaj", "sivka", "cvet", "šopek"] },
  },
  {
    id: "hut-stamp-booklet",
    name: "Hut stamp booklet",
    pitch: "The stamp booklet hikers carry from hut to hut: rubber stamps in one ink, each in its own ruled box, set slightly off true on a plain page.",
    family: "print",
    slovene: true,
    trades: { fit: ["tourist-farm", "restaurant", "bakery", "shop"], never: ["car-repair", "dental", "accountant", "physio", "builder"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bitter-nunito-sans", "archivo-archivo", "fraunces-nunito-sans"],
      palette: ["two-colour", "signal", "earth"],
      imagery: ["framed", "natural"],
      shape: ["soft", "square"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["fact/stamp", "mask/stamp", "motif/trail", "ornament/rubber-stamp"],
    references: ["markacija"],
    avoid: "Stamps over everything, rotated text nobody can read, a 'visited' stamp claiming a place or a date the client never gave.",
    cues: { goals: ["visit", "book"], angles: ["place"], materials: ["pot", "koča", "gora", "planina", "žig"], local: true },
  },
  {
    id: "pratika-almanac",
    name: "Pratika almanac",
    pitch: "The Slovene farmer's almanac: small one-colour pictures beside each entry, a dense two-column page, red kept for the days that matter.",
    family: "print",
    slovene: true,
    trades: { fit: ["tourist-farm", "bakery", "shop", "restaurant"], never: ["dental", "car-repair", "accountant", "physio", "hairdresser"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["garamond-karla", "bitter-karla", "newsreader-libre-franklin"],
      palette: ["earth", "two-colour", "warm"],
      imagery: ["framed", "natural"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["imagery/framed", "ornament/almanac-picture", "divider/column-rule", "composition/hours/almanac-week"],
    references: ["skorja", "markacija"],
    avoid: "A calendar gimmick: weather lore, moon phases and saints' days the client never wrote, little pictures used like emoji icons.",
    cues: { goals: ["visit", "order"], angles: ["place", "family-history", "craft"], materials: ["setev", "sadje", "zelenjava", "krompir", "jabolka", "ajda"], local: true },
  },
];

const SIGNAGE: readonly Stance[] = [
  {
    id: "trail-marker",
    name: "Trail marker",
    pitch: "The red-and-white trail blaze painted on rock: bold dots of colour guide the eye down the page, signs point the way.",
    family: "signage",
    slovene: true,
    trades: { fit: ["tourist-farm", "physio", "shop", "restaurant"], never: ["accountant", "dental"] },
    axes: {
      ground: ["white", "tint"],
      type: ["archivo-archivo", "bitter-nunito-sans", "space-grotesk-public-sans"],
      palette: ["signal", "two-colour", "earth"],
      imagery: ["full-bleed", "natural"],
      shape: ["square", "cut"],
      density: ["regular", "airy"],
      motion: "calm",
    },
    signatures: ["motif/trail", "fact/tag", "ornament/trail-blaze", "divider/ridge-line"],
    references: ["markacija"],
    avoid: "A hiking-club poster: arrows everywhere, a mountain silhouette behind every section.",
    cues: { goals: ["visit", "book"], angles: ["place"], materials: ["pot", "gora", "planina", "gozd", "kamen"], local: true },
  },
  {
    id: "enamel-house-plate",
    name: "Enamel house plate",
    pitch: "An enamel house-number plate: a deep blue field, a thin off-white rim, plain off-white capitals and big numerals, the corners gently rounded.",
    family: "signage",
    slovene: true,
    trades: { fit: ["*"], never: [] },
    axes: {
      ground: ["white", "dark"],
      type: ["archivo-archivo", "inter-tight-inter", "archivo-public-sans"],
      palette: ["cool", "deep", "two-colour"],
      imagery: ["framed", "natural"],
      shape: ["soft"],
      density: ["regular", "compact"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["fact/plate", "motif/plate", "typeTreatment/plate-numerals", "ornament/enamel-rim"],
    references: ["tablica", "cevi"],
    avoid: "A souvenir magnet: fake chips and rust, bevels and shine, a plate on every heading.",
    cues: { goals: ["visit", "call"], angles: ["place", "speed"], local: true },
  },
  {
    id: "shopfront-fascia",
    name: "Shopfront fascia",
    pitch: "Painted lettering on a shop fascia: the name in big flat capitals along a narrow coloured board, the trade set smaller under it, glass and goods below.",
    family: "signage",
    trades: { fit: ["shop", "bakery", "hairdresser", "restaurant", "car-repair", "builder"], never: [] },
    axes: {
      ground: ["white", "tint"],
      type: ["archivo-archivo", "bitter-nunito-sans", "bricolage-public-sans"],
      palette: ["signal", "deep", "two-colour"],
      imagery: ["full-bleed", "natural"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["typeTreatment/fascia-lettering", "imagery/full-bleed", "composition/opener/fascia-band"],
    references: ["skorja", "tablica"],
    avoid: "A fake chalkboard or neon sign, script lettering pretending to be hand-painted, a name too long to read at a glance.",
    cues: { goals: ["visit", "call"], angles: ["place", "family-history"], local: true },
  },
  {
    id: "bracket-sign",
    name: "Bracket sign",
    pitch: "An iron bracket sign hanging over an old-town street: one cut-out silhouette of the trade, the name painted beneath, a thin iron line framing both.",
    family: "signage",
    trades: { fit: ["restaurant", "bakery", "shop", "hairdresser", "tourist-farm", "builder"], never: ["car-repair", "dental", "accountant", "physio"] },
    axes: {
      ground: ["white", "tint"],
      type: ["garamond-karla", "bitter-karla", "fraunces-source-sans"],
      palette: ["deep", "earth", "two-colour"],
      imagery: ["framed", "natural"],
      shape: ["arch", "square"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["ornament/bracket-silhouette", "mask/arch", "imagery/framed", "divider/iron-line"],
    references: ["skorja", "jedilnik"],
    avoid: "A medieval theme park: blackletter, fake wrought curls, an invented guild crest or founding date.",
    cues: { goals: ["visit"], angles: ["craft", "place"], local: true },
  },
  {
    id: "direction-sign",
    name: "Direction sign",
    pitch: "A green road direction sign: a flat green field, off-white arrows and place names in a plain sign face, distances in big figures, nothing else.",
    family: "signage",
    trades: { fit: ["tourist-farm", "car-repair", "restaurant", "shop"], never: ["dental", "hairdresser", "physio", "accountant"] },
    axes: {
      ground: ["white", "dark"],
      type: ["archivo-public-sans", "inter-tight-dm-sans", "space-grotesk-public-sans"],
      palette: ["signal", "two-colour", "deep"],
      imagery: ["full-bleed", "natural"],
      shape: ["soft"],
      density: ["compact", "regular"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["fact/plate", "ornament/sign-arrow", "composition/contact/directions-board"],
    references: ["tablica", "markacija"],
    avoid: "A road-trip theme: arrows on every block, distances and exits the client never gave, a sign on every heading.",
    cues: { goals: ["visit", "call"], angles: ["place", "speed"], local: true },
  },
  {
    id: "department-store-letters",
    name: "Department store letters",
    pitch: "Big modular letters along a Yugoslav-era department store: a geometric sans, one brand colour, the name spaced along a long white fascia over wide windows.",
    family: "signage",
    slovene: true,
    trades: { fit: ["shop", "restaurant", "hairdresser", "bakery", "physio", "dental", "accountant"], never: ["tourist-farm"] },
    axes: {
      ground: ["white"],
      type: ["manrope-public-sans", "inter-tight-inter", "figtree-figtree"],
      palette: ["signal", "bright", "neutral"],
      imagery: ["full-bleed", "natural", "offset-block"],
      shape: ["square", "soft"],
      density: ["regular", "airy"],
      rhythm: ["inverse-accents"],
      motion: "calm",
    },
    signatures: ["typeTreatment/facade-letters", "imagery/offset-block", "composition/opener/facade-band"],
    references: ["lido", "ogledalo"],
    avoid: "Retro kitsch: brown and orange, rounded TV shapes, a made-up vintage logo or a real brand's lettering.",
    cues: { goals: ["visit", "browse"], angles: ["value", "place"] },
  },
  {
    id: "wayfinding",
    name: "Wayfinding",
    pitch: "A building's wayfinding system: one colour per area, big arrows and names readable from ten metres, the page laid out as where to go and when.",
    family: "signage",
    trades: { fit: ["dental", "physio", "accountant", "car-repair", "builder"], never: ["bakery", "tourist-farm"] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-dm-sans", "archivo-public-sans", "manrope-public-sans"],
      palette: ["signal", "cool", "bright"],
      imagery: ["natural"],
      shape: ["square", "soft"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/plate", "ornament/sign-arrow", "composition/contact/find-us", "icon/practical-set"],
    references: ["nasmeh", "pregib"],
    avoid: "An airport: grey on grey, a pictogram in every row like emoji, a colour code nobody explains.",
    cues: { goals: ["visit", "book", "call"], angles: ["speed", "place"] },
  },
  {
    id: "market-stall-cards",
    name: "Market stall cards",
    pitch: "Price cards pushed into crates at the open-air market: big bold figures on bright card, each at its own slight angle, one card per item.",
    family: "signage",
    slovene: true,
    trades: { fit: ["shop", "bakery", "tourist-farm", "restaurant"], never: ["dental", "physio", "accountant", "car-repair", "builder", "hairdresser"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bricolage-figtree", "archivo-archivo", "bitter-nunito-sans"],
      palette: ["bright", "warm", "signal"],
      imagery: ["natural", "full-bleed"],
      shape: ["square", "cut"],
      density: ["compact", "regular"],
      rhythm: ["alternate"],
      motion: "lively",
    },
    signatures: ["fact/tag", "imagery/natural", "typeTreatment/price-figures", "composition/prices/stall-cards"],
    references: ["etiketa", "skorja"],
    avoid: "Clip-art fruit, chalkboard fonts, invented prices written to fill the cards.",
    cues: { goals: ["visit", "order"], angles: ["value", "place"], materials: ["sadje", "zelenjava", "sir", "jajca", "med", "krompir"], local: true },
  },
  {
    id: "safety-signage",
    name: "Safety signage",
    pitch: "Workplace safety signs: one shape per meaning (a disc, a triangle, a square), signal yellow and a dark ink, diagonal hazard stripes only on the edge that needs attention.",
    family: "signage",
    trades: { fit: ["builder", "car-repair"], never: [] },
    axes: {
      ground: ["white", "dark"],
      type: ["archivo-archivo", "space-grotesk-public-sans", "archivo-public-sans"],
      palette: ["signal", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square", "cut"],
      density: ["compact", "regular"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["mask/circle", "shape/cut", "ornament/sign-shapes", "divider/hazard-stripe"],
    references: ["tablica", "cevi"],
    avoid: "A building-site warning: hazard tape on every block, alarm colours everywhere, signs that threaten instead of inform.",
    cues: { goals: ["call", "enquire"], angles: ["speed", "speciality"], materials: ["elektrika", "plin", "kabel", "varjenje", "streha"] },
  },
  {
    id: "tool-shadow-board",
    name: "Tool shadow board",
    pitch: "A pegboard tool wall with each tool's outline painted where it hangs: the offer laid out like tools on a shadow board, every item in its place.",
    family: "signage",
    trades: { fit: ["builder", "car-repair", "hairdresser", "shop"], never: ["dental", "restaurant", "bakery", "accountant", "tourist-farm"], subNever: ["florist", "deli"] },
    axes: {
      ground: ["white", "tint"],
      type: ["space-grotesk-public-sans", "archivo-public-sans", "ibm-plex-sans"],
      palette: ["signal", "two-colour", "cool"],
      imagery: ["natural"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/pipes", "ornament/tool-outline", "texture/pegboard", "composition/services/shadow-board"],
    references: ["cevi", "tablica"],
    avoid: "A hardware catalogue: a photo grid of tools, every outline drawn, pegboard holes behind the text.",
    cues: { goals: ["call", "enquire"], angles: ["craft", "speciality"], materials: ["orodje", "ključ", "škarje", "kladivo", "vijak", "žaga"] },
  },
  {
    id: "brass-door-plate",
    name: "Brass door plate",
    pitch: "The engraved plate beside a practice door: a name and a profession in fine engraved capitals, a thin frame, four screw heads, one metal tone.",
    family: "signage",
    trades: { fit: ["dental", "physio", "accountant"], never: ["car-repair", "bakery", "restaurant", "tourist-farm", "builder", "shop"] },
    axes: {
      ground: ["white", "dark"],
      type: ["garamond-figtree", "newsreader-libre-franklin", "inter-tight-dm-sans"],
      palette: ["deep", "muted", "neutral"],
      imagery: ["framed", "monochrome", "natural"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/plate", "typeTreatment/engraved-capitals", "ornament/screw-frame"],
    references: ["racun", "nasmeh"],
    avoid: "A fake metal plate: gradients for shine, heavy drop shadows, embossed bevels, a title the client doesn't hold.",
    cues: { goals: ["book", "call", "enquire"], angles: ["person", "speciality"] },
  },
  {
    id: "registration-plate",
    name: "Registration plate",
    pitch: "Embossed number-plate lettering: dark condensed characters on a white field inside a thin rim, the business name set as a short plate across the hero.",
    family: "signage",
    trades: { fit: ["car-repair"], never: [] },
    axes: {
      ground: ["white", "dark"],
      type: ["archivo-archivo", "archivo-public-sans", "space-grotesk-public-sans"],
      palette: ["signal", "cool", "two-colour"],
      imagery: ["natural", "full-bleed"],
      shape: ["soft"],
      density: ["compact"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["motif/plate", "fact/plate", "typeTreatment/plate-numerals"],
    references: ["tablica"],
    avoid: "A licence-plate gimmick: a fake registration, a town code the client isn't in, plates on every heading.",
    cues: { goals: ["call", "book"], angles: ["speed", "value"], materials: ["guma", "olje", "avto", "zavore", "pnevmatike", "karoserija"] },
  },
];

const CRAFT: readonly Stance[] = [
  {
    id: "beehive-panel",
    name: "Beehive panel",
    pitch: "The painted fronts of Slovene beehives: a small scene in a framed panel, saturated folk colours on a plain ground, panels side by side.",
    family: "craft",
    slovene: true,
    trades: { fit: ["bakery", "tourist-farm", "shop", "restaurant"], never: ["car-repair", "dental", "accountant", "physio"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-source-sans", "bitter-karla", "garamond-karla"],
      palette: ["bright", "warm", "earth"],
      imagery: ["framed", "rounded"],
      shape: ["soft", "arch"],
      density: ["regular"],
      motion: "still",
    },
    signatures: ["ornament/beehive-panel", "mask/arch", "imagery/framed", "fact/seal"],
    references: ["etiketa", "skorja"],
    avoid: "A souvenir shop: painted panels on every block, no air, every colour at full strength at once.",
    cues: { goals: ["visit", "order"], angles: ["family-history", "craft", "place"], materials: ["med", "les", "kruh", "potica", "vosek"], local: true },
  },
  {
    id: "idrija-lace",
    name: "Idrija lace",
    pitch: "Idrija bobbin lace: one fine tracery of narrow braided lines framing a plain field on a deep ground, everything around it quiet.",
    family: "craft",
    slovene: true,
    trades: { fit: ["bakery", "shop", "restaurant", "hairdresser", "tourist-farm"], never: ["car-repair", "builder", "accountant", "physio", "dental"] },
    axes: {
      ground: ["dark", "white"],
      type: ["garamond-karla", "lora-karla", "garamond-figtree"],
      palette: ["deep", "monochrome", "muted"],
      imagery: ["framed", "arched"],
      shape: ["arch", "soft"],
      density: ["airy"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["mask/arch", "ornament/lace-tracery", "divider/lace-band"],
    references: ["ogledalo", "jedilnik"],
    avoid: "Doily kitsch: lace on every corner, pastel pink, a frilly border round each photo.",
    cues: { goals: ["visit", "browse", "book"], angles: ["craft", "place"], materials: ["čipka", "nit", "blago", "poroka"], local: true },
  },
  {
    id: "painted-chest",
    name: "Painted dowry chest",
    pitch: "A painted Gorenjska dowry chest: carnations and tulips in framed panels on a deep blue or green ground, the flowers kept to the panel corners.",
    family: "craft",
    slovene: true,
    trades: { fit: ["bakery", "tourist-farm", "restaurant", "shop"], never: ["car-repair", "dental", "accountant", "physio", "builder"] },
    axes: {
      ground: ["dark", "tint"],
      type: ["fraunces-source-sans", "bitter-karla", "lora-karla"],
      palette: ["deep", "bright", "warm"],
      imagery: ["framed", "arched"],
      shape: ["arch", "square"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["imagery/framed", "ornament/carnation-corner", "divider/painted-band"],
    references: ["markacija", "skorja"],
    avoid: "A folk costume party: every border painted, red hearts everywhere, a 'domače' headline doing the work.",
    cues: { goals: ["visit", "order"], angles: ["craft", "family-history", "place"], materials: ["les", "skrinja", "kruh", "potica"], local: true },
  },
  {
    id: "pisanice",
    name: "Bela krajina pisanice",
    pitch: "Wax-resist pisanice from Bela krajina: fine geometric bands and rosettes in deep red and dark ink on white, drawn as thin lines, never filled.",
    family: "craft",
    slovene: true,
    trades: { fit: ["bakery", "shop", "tourist-farm", "restaurant"], never: ["car-repair", "dental", "accountant", "physio", "builder"] },
    axes: {
      ground: ["white"],
      type: ["garamond-karla", "bitter-karla", "lora-dm-sans"],
      palette: ["two-colour", "deep", "warm"],
      imagery: ["rounded", "framed"],
      shape: ["soft", "arch"],
      density: ["airy", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["mask/circle", "ornament/pisanica-band", "divider/rosette-line"],
    references: ["skorja", "etiketa"],
    avoid: "An Easter card: eggs drawn everywhere, pastel colours, a seasonal greeting as the headline.",
    cues: { goals: ["visit", "order"], angles: ["craft", "place"], materials: ["jajca", "pirhi", "vosek", "med"], local: true },
  },
  {
    id: "prekmurje-pottery",
    name: "Prekmurje pottery",
    pitch: "Prekmurje clay pots: earth red and smoked dark grey, rounded vessel silhouettes holding the photos, a fine incised band around each form.",
    family: "craft",
    slovene: true,
    trades: { fit: ["restaurant", "bakery", "shop", "tourist-farm"], never: ["car-repair", "dental", "accountant", "physio", "builder"] },
    axes: {
      ground: ["tint", "white"],
      type: ["fraunces-nunito-sans", "bitter-karla", "lora-karla"],
      palette: ["earth", "warm", "deep"],
      imagery: ["rounded", "arched"],
      shape: ["arch", "soft"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["mask/arch", "ornament/vessel-silhouette", "divider/incised-band"],
    references: ["skorja", "jedilnik"],
    avoid: "Terracotta overload: orange on everything, every photo in a round pot, clip-art jugs.",
    cues: { goals: ["visit", "order"], angles: ["craft", "place"], materials: ["glina", "lonec", "keramika", "bučno olje", "gibanica", "kruh"], local: true },
  },
  {
    id: "letterpress-proof",
    name: "Letterpress proof",
    pitch: "A letterpress proof: wood type in heavy sizes, two inks overprinting where they cross, generous paper around a few short lines.",
    family: "craft",
    trades: { fit: ["bakery", "shop", "restaurant", "hairdresser", "tourist-farm", "builder"], never: ["dental"] },
    axes: {
      ground: ["white"],
      type: ["bitter-karla", "archivo-archivo", "fraunces-source-sans"],
      palette: ["two-colour", "bright", "warm"],
      imagery: ["duotone", "natural"],
      shape: ["square"],
      density: ["airy", "regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["treatment/duotone", "typeTreatment/wood-type", "texture/press-grain"],
    references: ["crke", "skorja"],
    avoid: "Hipster pastiche: distressed texture on every letter, fake wood grain, ampersands as decoration.",
    cues: { goals: ["visit", "order", "browse"], angles: ["craft", "speciality"] },
  },
  {
    id: "stencil-crate",
    name: "Stencil crate",
    pitch: "Spray-stencilled crate marking: bridged capitals, one ink straight onto bare boards and steel, the client's own words stamped on the boxes.",
    family: "craft",
    trades: { fit: ["builder", "car-repair", "shop", "restaurant"], never: ["dental", "physio"], subNever: ["florist"] },
    axes: {
      ground: ["white", "tint", "dark"],
      type: ["archivo-archivo", "space-grotesk-public-sans", "bitter-nunito-sans"],
      palette: ["signal", "two-colour", "earth"],
      imagery: ["natural", "monochrome"],
      shape: ["cut", "square"],
      density: ["compact"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["mask/cut", "typeTreatment/stencil-capitals", "texture/raw-board"],
    references: ["cevi", "tablica"],
    avoid: "Army surplus: camouflage greens, stencil on every word, spray noise over the text.",
    cues: { goals: ["call", "order"], angles: ["speed", "value"], materials: ["les", "deske", "jeklo", "zaboj", "palete"] },
  },
  {
    id: "cut-paper",
    name: "Cut paper",
    pitch: "Shapes cut from coloured paper with scissors: flat overlapping pieces with slightly uneven edges, three colours, no outlines, the photos cut the same way.",
    family: "craft",
    trades: { fit: ["bakery", "shop", "physio", "dental", "hairdresser", "restaurant"], never: ["car-repair", "accountant", "builder"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bricolage-figtree", "fraunces-nunito-sans", "figtree-figtree"],
      palette: ["bright", "warm", "cool"],
      imagery: ["rounded", "offset-block"],
      shape: ["soft", "cut"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "lively",
    },
    signatures: ["mask/cut", "imagery/offset-block", "ornament/cut-shape"],
    references: ["val", "lido"],
    avoid: "A children's craft hour: a rainbow of colours, googly shapes, everything wobbling and nothing still.",
    cues: { goals: ["book", "visit"], angles: ["person", "craft"] },
  },
  {
    id: "cross-stitch",
    name: "Cross-stitch sampler",
    pitch: "A cross-stitched sampler: motifs built from small square stitches in two thread colours on a white weave, a stitched border line round the main block.",
    family: "craft",
    trades: { fit: ["bakery", "tourist-farm", "shop", "restaurant"], never: ["car-repair", "accountant", "dental", "physio", "builder"] },
    axes: {
      ground: ["white"],
      type: ["bitter-karla", "fraunces-nunito-sans", "lora-karla"],
      palette: ["two-colour", "warm", "muted"],
      imagery: ["framed", "natural"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["imagery/framed", "ornament/stitch-motif", "divider/stitch-line", "texture/linen-weave"],
    references: ["skorja", "markacija"],
    avoid: "Kitsch: stitched hearts and 'Dom, sladki dom', pixel motifs that read as a video game.",
    cues: { goals: ["visit", "order"], angles: ["craft", "family-history"], materials: ["blago", "lan", "nit", "prt"] },
  },
  {
    id: "glazed-tile",
    name: "Glazed tile",
    pitch: "Glazed wall tiles: square panels with a repeating two-colour pattern, the grid of grout lines showing, photos set into the wall like tiles.",
    family: "craft",
    trades: { fit: ["restaurant", "bakery", "dental", "physio", "shop", "hairdresser", "builder"], never: ["car-repair", "accountant"], subNever: ["electrical", "roofing"] },
    axes: {
      ground: ["white", "tint"],
      type: ["inter-tight-dm-sans", "manrope-public-sans", "lora-dm-sans"],
      palette: ["cool", "bright", "two-colour"],
      imagery: ["framed", "natural"],
      shape: ["square"],
      density: ["regular", "compact"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["shape/square", "ornament/tile-pattern", "texture/tile-grid"],
    references: ["nasmeh", "val"],
    avoid: "A bathroom catalogue: pattern behind every word, shiny glaze highlights, a grid with no place to rest.",
    cues: { goals: ["visit", "book"], angles: ["craft", "place"], materials: ["ploščice", "keramika", "kopalnica"] },
  },
  {
    id: "woodcut",
    name: "Woodcut",
    pitch: "A woodcut print: bold drawings in dark ink and one colour, heavy shapes with the gouge marks left in, text in a sturdy serif beside them.",
    family: "craft",
    trades: { fit: ["tourist-farm", "bakery", "restaurant", "builder", "shop"], never: ["dental", "physio", "accountant", "hairdresser"] },
    axes: {
      ground: ["white"],
      type: ["bitter-karla", "garamond-karla", "fraunces-source-sans"],
      palette: ["two-colour", "earth", "deep"],
      imagery: ["monochrome", "duotone"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["treatment/duotone", "ornament/woodcut-object", "texture/gouge"],
    references: ["markacija", "skorja"],
    avoid: "A medieval chapbook: blackletter, saints and dragons, every picture framed in a rope border.",
    cues: { goals: ["visit", "order"], angles: ["craft", "place"], materials: ["les", "kruh", "sir", "volna"] },
  },
  {
    id: "ribnica-woodenware",
    name: "Ribnica woodenware",
    pitch: "Ribnica woodenware: turned spoons, sieves and bowls laid out in rows, pale wood shapes on a deep coloured ground, one painted stripe on each.",
    family: "craft",
    slovene: true,
    trades: { fit: ["bakery", "restaurant", "shop", "tourist-farm", "builder"], never: ["car-repair", "dental", "accountant", "physio", "hairdresser"], subOnly: ["carpentry"] },
    axes: {
      ground: ["dark", "tint"],
      type: ["bitter-karla", "fraunces-nunito-sans", "lora-karla"],
      palette: ["earth", "deep", "warm"],
      imagery: ["natural", "rounded"],
      shape: ["soft", "arch"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["motif/spoon", "motif/joint", "ornament/turned-object", "divider/painted-stripe"],
    references: ["jedilnik", "skorja"],
    avoid: "A log cabin: wood grain as the page ground, burnt-in lettering, a beige page and a cabin in the hero.",
    cues: { goals: ["visit", "order"], angles: ["craft", "family-history"], materials: ["les", "žlica", "sito", "rešeto", "skleda", "lipa"], local: true },
  },
  {
    id: "lect-heart",
    name: "Lect heart",
    pitch: "Honey-dough lect hearts: a deep red glazed shape with fine piped off-white lines and a small round mirror at its centre, framing one short line.",
    family: "craft",
    slovene: true,
    trades: { fit: ["bakery", "shop", "tourist-farm"], never: [], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-source-sans", "lora-dm-sans", "garamond-karla"],
      palette: ["deep", "two-colour", "warm"],
      imagery: ["rounded", "framed"],
      shape: ["soft", "arch"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["mask/circle", "ornament/piped-line", "divider/piped-border"],
    references: ["skorja", "etiketa"],
    avoid: "Valentine's kitsch: hearts on every element, pink, a love message as the headline.",
    cues: { goals: ["order", "visit"], angles: ["craft", "family-history"], materials: ["med", "lect", "medenjaki", "testo", "piškoti"], local: true },
  },
  {
    id: "sewing-pattern",
    name: "Sewing pattern",
    pitch: "A paper sewing pattern: thin dashed cutting lines, notch marks and grain arrows, the pieces as flat shapes laid across a pale blue-grey sheet.",
    family: "craft",
    trades: { fit: ["shop", "hairdresser"], never: [], subOnly: ["boutique"] },
    axes: {
      ground: ["tint", "white"],
      type: ["space-grotesk-plex", "inter-tight-dm-sans", "bricolage-public-sans"],
      palette: ["cool", "muted", "two-colour"],
      imagery: ["offset-block", "natural"],
      shape: ["cut"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["mask/cut", "motif/tag", "ornament/dashed-cut-line"],
    references: ["ogledalo", "etiketa"],
    avoid: "A tissue-paper beige page, measuring tapes along every edge, sewing-kit clip art.",
    cues: { goals: ["browse", "book"], angles: ["craft", "person"], materials: ["blago", "obleka", "šivanje", "krojač", "škarje"] },
  },
  {
    id: "enamel-kitchenware",
    name: "Enamel kitchenware",
    pitch: "Enamelled kitchen pots of the Yugoslav years: deep red with small off-white dots, a dark rim on every edge; the dots and rims become the page's ornament.",
    family: "craft",
    slovene: true,
    trades: { fit: ["restaurant", "bakery", "shop", "tourist-farm"], never: ["car-repair", "dental", "accountant", "physio", "builder", "hairdresser"], subNever: ["boutique", "florist"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bricolage-figtree", "bitter-nunito-sans", "fraunces-nunito-sans"],
      palette: ["bright", "two-colour", "warm"],
      imagery: ["rounded", "natural"],
      shape: ["soft"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "calm",
    },
    signatures: ["mask/circle", "ornament/dot-field", "divider/enamel-rim"],
    references: ["jedilnik", "lido"],
    avoid: "Polka-dot wallpaper on every block, a chipped-enamel texture, a 'like grandma's kitchen' headline.",
    cues: { goals: ["visit", "order"], angles: ["family-history", "value"], materials: ["juha", "lonec", "golaž", "enolončnica", "štruklji", "malica"] },
  },
];

const MODERNIST: readonly Stance[] = [
  {
    id: "plecnik-classicism",
    name: "Plečnik-era classicism",
    pitch: "Ljubljana's columns and stone lettering: a calm classical grid, carved capitals, one column of colour, generous margins.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["accountant", "dental", "restaurant", "shop", "physio"], never: ["car-repair"] },
    axes: {
      ground: ["white", "tint"],
      type: ["garamond-figtree", "newsreader-libre-franklin", "garamond-karla"],
      palette: ["deep", "muted", "neutral"],
      imagery: ["arched", "framed", "monochrome"],
      shape: ["square", "arch"],
      density: ["airy", "regular"],
      rhythm: ["flat", "alternate"],
      motion: "still",
    },
    signatures: ["mask/arch", "typeTreatment/carved-capitals", "divider/double-rule", "imagery/arched"],
    references: ["racun", "jedilnik"],
    avoid: "A bank or a funeral home: grey marble, every heading centred, nothing that says what the business does.",
    cues: { goals: ["book", "enquire", "visit"], angles: ["person", "speciality"], materials: ["kamen", "marmor"], local: true },
  },
  {
    id: "swiss-grid",
    name: "Swiss grid",
    pitch: "A strict modular grid, one grotesk in a few sizes, flush-left text and numbers set large, colour used only to point.",
    family: "modernist",
    trades: { fit: ["*"], never: ["bakery", "tourist-farm"] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-inter", "inter-tight-dm-sans", "ibm-plex-sans"],
      palette: ["neutral", "signal", "monochrome"],
      imagery: ["natural", "monochrome", "full-bleed"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/numeral", "typeTreatment/giant-numeral", "composition/opener/grid-poster"],
    references: ["racun", "proge"],
    avoid: "A software landing page: three feature cards, a centred hero, a gradient button, '01' labels over the sections.",
    cues: { goals: ["call", "book", "enquire"], angles: ["speed", "value", "speciality"] },
  },
  {
    id: "bauhaus-geometry",
    name: "Bauhaus geometry",
    pitch: "Circle, square and triangle as the building blocks: a strict grid, heavy sans headings, one primary-coloured figure per section doing a job.",
    family: "modernist",
    trades: { fit: ["hairdresser", "physio", "shop", "builder", "dental", "accountant"], never: ["tourist-farm", "bakery"] },
    axes: {
      ground: ["white"],
      type: ["archivo-archivo", "inter-tight-inter", "space-grotesk-public-sans"],
      palette: ["bright", "signal", "two-colour"],
      imagery: ["offset-block", "monochrome", "natural"],
      shape: ["square", "arch"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["mask/circle", "shape/square", "ornament/primary-figure", "composition/opener/figure-and-name"],
    references: ["lido", "proge"],
    avoid: "A primary-colour flag: red, yellow and blue on every block, shapes floating for no reason.",
    cues: { goals: ["book", "enquire"], angles: ["speciality", "person"] },
  },
  {
    id: "yugoslav-modernism",
    name: "Yugoslav modernism",
    pitch: "Public buildings of the Yugoslav era: long horizontal bands, raw grey with one strong orange, deep window rhythms, big confident grotesk headings.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["builder", "accountant", "physio", "dental", "car-repair", "shop"], never: ["bakery", "tourist-farm"] },
    axes: {
      ground: ["white", "dark"],
      type: ["space-grotesk-public-sans", "archivo-public-sans", "inter-tight-inter"],
      palette: ["neutral", "signal", "deep"],
      imagery: ["monochrome", "full-bleed", "offset-block"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["imagery/monochrome", "texture/board-concrete", "composition/opener/horizontal-bands"],
    references: ["cevi", "globina"],
    avoid: "Brutalist nostalgia: concrete texture everywhere, poster red, monuments and stars as decoration.",
    cues: { goals: ["enquire", "call", "book"], angles: ["speciality", "value"], materials: ["beton", "steklo", "jeklo"] },
  },
  {
    id: "ljubljana-sixties-poster",
    name: "Sixties Slovene poster",
    pitch: "Slovene poster design of the sixties: one bold abstract sign built from two flat shapes, a precise grotesk set small beside it, a wide open field of colour.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["hairdresser", "shop", "restaurant", "physio", "accountant", "dental"], never: [] },
    axes: {
      ground: ["white", "tint"],
      type: ["inter-tight-dm-sans", "manrope-public-sans", "archivo-public-sans"],
      palette: ["bright", "two-colour", "signal"],
      imagery: ["duotone", "offset-block"],
      shape: ["square", "arch"],
      density: ["airy"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["treatment/tint", "ornament/abstract-sign", "composition/opener/sign-and-field"],
    references: ["lido", "crke"],
    avoid: "A retro poster pastiche: halftone dots, sun-faded colours, fake folds, someone else's poster redrawn.",
    cues: { goals: ["book", "browse", "visit"], angles: ["person", "speciality"] },
  },
  {
    id: "yugoslav-packaging",
    name: "Yugoslav-era packaging",
    pitch: "Grocery packaging of the Yugoslav years: a chunky sans name, a simple drawing of the product, two flat colours, a clean band saying what's inside.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["bakery", "shop", "restaurant", "tourist-farm"], never: ["dental", "physio", "accountant"], subNever: ["boutique", "florist"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bricolage-public-sans", "archivo-archivo", "bitter-nunito-sans"],
      palette: ["two-colour", "bright", "warm"],
      imagery: ["duotone", "rounded"],
      shape: ["soft", "square"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["motif/label", "treatment/duotone", "ornament/product-drawing", "typeTreatment/chunky-name"],
    references: ["etiketa", "skorja"],
    avoid: "A nostalgia shop: real brands' logos, fake wear, a 'kot v starih časih' headline.",
    cues: { goals: ["order", "visit", "browse"], angles: ["value", "speciality"], materials: ["moka", "kava", "marmelada", "sok", "keksi"] },
  },
  {
    id: "modular-kiosk",
    name: "Modular kiosk",
    pitch: "The Slovene modular street kiosk: bright red modules with rounded corners and rounded windows, set side by side, the name in a plain lower panel.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["shop", "bakery", "restaurant", "hairdresser"], never: [] },
    axes: {
      ground: ["white"],
      type: ["manrope-public-sans", "figtree-figtree", "bricolage-figtree"],
      palette: ["bright", "signal", "two-colour"],
      imagery: ["rounded", "natural"],
      shape: ["soft"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "calm",
    },
    signatures: ["imagery/rounded", "ornament/rounded-window", "composition/services/kiosk-modules"],
    references: ["lido", "val"],
    avoid: "Pill buttons and pill-shaped cards, every corner fully round, toy red on everything.",
    cues: { goals: ["visit", "order"], angles: ["speed", "value"], materials: ["kava", "časopis", "burek", "sladoled"] },
  },
  {
    id: "ljubljana-secession",
    name: "Ljubljana Secession",
    pitch: "The Secession facades of central Ljubljana: tall narrow panels, stylised plant lines, soft colour fields framed by thin ornamental bands.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["hairdresser", "dental", "restaurant", "shop", "bakery", "physio"], never: ["car-repair", "builder"] },
    axes: {
      ground: ["white", "tint"],
      type: ["garamond-figtree", "lora-dm-sans", "newsreader-libre-franklin"],
      palette: ["muted", "cool", "warm"],
      imagery: ["arched", "framed"],
      shape: ["arch"],
      density: ["airy"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["mask/arch", "motif/stem", "ornament/stem-line", "divider/facade-band"],
    references: ["ogledalo", "jedilnik"],
    avoid: "A wedding invitation: script capitals, swirls on every corner, gold and pastel everything.",
    cues: { goals: ["book", "visit"], angles: ["place", "person"], local: true },
  },
  {
    id: "functional-catalogue",
    name: "Functional catalogue",
    pitch: "A functionalist product catalogue: each object photographed on a plain ground, a quiet grid, small precise type, one signal colour for what to press.",
    family: "modernist",
    trades: { fit: ["shop", "physio", "dental", "car-repair", "builder", "hairdresser"], never: [] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-inter", "ibm-plex-sans", "figtree-figtree"],
      palette: ["neutral", "signal", "monochrome"],
      imagery: ["natural", "framed"],
      shape: ["soft", "square"],
      density: ["regular", "airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["imagery/natural", "ornament/signal-dot", "composition/services/object-grid"],
    references: ["nasmeh", "etiketa"],
    avoid: "A webshop template: a grid of equal product cards with drop shadows, sale badges, stars nobody gave.",
    cues: { goals: ["browse", "order", "enquire"], angles: ["speciality", "value"] },
  },
  {
    id: "transit-diagram",
    name: "Transit diagram",
    pitch: "A transit diagram: thick coloured lines at right angles and 45°, stops as rings, the steps of the service laid out as stations along one route.",
    family: "modernist",
    trades: { fit: ["physio", "builder", "accountant", "dental", "car-repair", "tourist-farm"], never: ["bakery", "hairdresser"] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-dm-sans", "manrope-public-sans", "space-grotesk-public-sans"],
      palette: ["bright", "signal", "cool"],
      imagery: ["natural"],
      shape: ["soft", "square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["mask/circle", "ornament/route-line", "divider/route-stop", "composition/process/route"],
    references: ["pregib", "proge"],
    avoid: "A subway theme: a fake map with invented stops, line numbers as labels, every list turned into a route.",
    cues: { goals: ["book", "enquire"], angles: ["speed", "speciality"] },
  },
  {
    id: "adriatic-resort-modernism",
    name: "Adriatic resort modernism",
    pitch: "Coastal hotels of the Yugoslav years: white terraces in horizontal bands, sea blue and sun yellow, balcony rhythms, a clean sans with room to breathe.",
    family: "modernist",
    slovene: true,
    trades: { fit: ["tourist-farm", "restaurant", "physio", "hairdresser", "shop"], never: ["car-repair", "builder", "accountant"] },
    axes: {
      ground: ["white"],
      type: ["manrope-public-sans", "inter-tight-dm-sans", "figtree-figtree"],
      palette: ["bright", "cool", "two-colour"],
      imagery: ["full-bleed", "natural"],
      shape: ["soft", "square"],
      density: ["airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["imagery/full-bleed", "ornament/balcony-band", "composition/opener/terraces"],
    references: ["lido", "popoldan"],
    avoid: "A holiday brochure: palm trees, sunset gradients, anchors and rope, a 'raj na zemlji' headline.",
    cues: { goals: ["book", "visit"], angles: ["place"], materials: ["morje", "sol", "riba", "oljka"], local: true },
  },
  {
    id: "axonometric",
    name: "Axonometric drawing",
    pitch: "An axonometric drawing: the room, shopfront or job drawn in crisp lines at 30°, flat colour fills, small notes pointing at the parts that matter.",
    family: "modernist",
    trades: { fit: ["builder", "car-repair", "shop", "accountant", "restaurant"], never: [], subNever: ["florist"] },
    axes: {
      ground: ["white", "tint"],
      type: ["space-grotesk-plex", "inter-tight-inter", "ibm-plex-sans"],
      palette: ["cool", "signal", "muted"],
      imagery: ["natural"],
      shape: ["cut", "square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/pipes", "ornament/axonometric-object", "composition/opener/drawn-object"],
    references: ["cevi", "proge"],
    avoid: "An architecture render: glossy 3D, shadows and glass, a building the client doesn't have.",
    cues: { goals: ["enquire", "visit"], angles: ["speciality", "craft"], materials: ["streha", "kopalnica", "kuhinja", "fasada", "instalacije"] },
  },
];

const PLACE: readonly Stance[] = [
  {
    id: "karst-stone",
    name: "Karst stone",
    pitch: "Dry-stone walls and red soil of the Karst: a pale stone ground, deep red and olive, heavy blocks set like masonry.",
    family: "place",
    slovene: true,
    trades: { fit: ["restaurant", "tourist-farm", "shop", "builder"], never: ["dental", "car-repair", "hairdresser"] },
    axes: {
      ground: ["tint", "white"],
      type: ["bitter-karla", "fraunces-source-sans", "newsreader-libre-franklin"],
      palette: ["earth", "deep", "muted"],
      imagery: ["natural", "full-bleed", "offset-block"],
      shape: ["square", "cut"],
      density: ["regular", "airy"],
      motion: "still",
    },
    signatures: ["texture/stone", "imagery/offset-block", "divider/stone-course", "mask/cut"],
    references: ["etiketa", "jedilnik"],
    avoid: "A wine-bar cliché: dark wood, gold script, a grape vine on every heading.",
    cues: { goals: ["visit", "book", "order"], angles: ["place", "craft", "family-history"], materials: ["kamen", "teran", "pršut", "vino", "sol", "oljka"], local: true },
  },
  {
    id: "julian-alps",
    name: "High alpine light",
    pitch: "High alpine light: a cold white ground, slate-grey rock and one gentian blue, a ridge line drawn across the top of sections, wide photos of open sky.",
    family: "place",
    slovene: true,
    trades: { fit: ["tourist-farm", "physio", "restaurant", "shop"], never: ["car-repair", "accountant"], subNever: ["boutique"] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-inter", "manrope-public-sans", "fraunces-source-sans"],
      palette: ["cool", "muted", "two-colour"],
      imagery: ["full-bleed", "natural"],
      shape: ["square", "cut"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["motif/trail", "imagery/full-bleed", "divider/ridge-line"],
    references: ["markacija", "popoldan"],
    avoid: "A ski brochure: snowflakes, a mountain silhouette behind every heading, a stock panorama, blue gradients.",
    cues: { goals: ["visit", "book"], angles: ["place"], materials: ["gora", "planina", "sir", "mleko", "smučanje"], local: true },
  },
  {
    id: "vineyard-rows",
    name: "Vineyard rows",
    pitch: "Hillside vineyard rows seen from above: parallel lines bending with the slope, stripes of green and bare soil, the content set along the rows.",
    family: "place",
    slovene: true,
    trades: { fit: ["tourist-farm", "restaurant", "shop"], never: ["car-repair", "dental", "accountant", "physio"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-source-sans", "lora-karla", "garamond-figtree"],
      palette: ["earth", "warm", "muted"],
      imagery: ["full-bleed", "natural"],
      shape: ["soft"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["imagery/full-bleed", "ornament/row-lines", "divider/contour-line"],
    references: ["etiketa", "jedilnik"],
    avoid: "A wine-bar cliché: grapes on every heading, gold script, dark wood, a toast in the headline.",
    cues: { goals: ["visit", "book", "order"], angles: ["place", "craft"], materials: ["vino", "trta", "grozdje", "klet", "vinograd"], local: true },
  },
  {
    id: "soca-green",
    name: "Soča green",
    pitch: "The emerald of the Soča over white pebbles: a clear cold green, pale stone grey, rounded pebble shapes holding the photos, smooth open space.",
    family: "place",
    slovene: true,
    trades: { fit: ["tourist-farm", "physio", "restaurant", "dental", "hairdresser"], never: ["car-repair", "accountant"] },
    axes: {
      ground: ["white", "tint"],
      type: ["manrope-public-sans", "figtree-figtree", "lora-dm-sans"],
      palette: ["cool", "muted", "bright"],
      imagery: ["rounded", "full-bleed"],
      shape: ["soft"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["mask/circle", "imagery/rounded", "ornament/pebble-shape"],
    references: ["gladina", "val"],
    avoid: "A rafting ad: splash photos, wave dividers everywhere, an adventure slogan in capitals.",
    cues: { goals: ["visit", "book"], angles: ["place", "person"], materials: ["reka", "voda", "kamenje", "postrv"], local: true },
  },
  {
    id: "pannonian-plain",
    name: "Pannonian plain",
    pitch: "The flat fields of Prekmurje: a low horizon a third up the page, long horizontal bands of field colour, one tree or stork's nest as the only vertical.",
    family: "place",
    slovene: true,
    trades: { fit: ["tourist-farm", "bakery", "restaurant", "shop"], never: ["dental", "car-repair", "accountant"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bitter-nunito-sans", "fraunces-nunito-sans", "lora-karla"],
      palette: ["earth", "warm", "muted"],
      imagery: ["full-bleed", "natural"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["imagery/full-bleed", "divider/horizon-line", "ornament/lone-tree"],
    references: ["popoldan", "markacija"],
    avoid: "A farm stock site: tractors, golden-hour wheat, a sunset gradient behind the name.",
    cues: { goals: ["visit", "order"], angles: ["place", "family-history"], materials: ["bučno olje", "ajda", "koruza", "polje", "gibanica"], local: true },
  },
  {
    id: "salt-pans",
    name: "Salt pans",
    pitch: "Coastal salt pans: a grid of shallow rectangular basins, white salt and mirror-grey water, thin earthen dividers, a wide pale sky.",
    family: "place",
    slovene: true,
    trades: { fit: ["restaurant", "shop", "tourist-farm", "physio"], never: ["car-repair", "builder", "accountant"] },
    axes: {
      ground: ["white", "tint"],
      type: ["inter-tight-dm-sans", "garamond-figtree", "manrope-public-sans"],
      palette: ["cool", "neutral", "muted"],
      imagery: ["full-bleed", "natural", "monochrome"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["imagery/monochrome", "texture/salt-grid", "divider/hairline"],
    references: ["gladina", "mirno"],
    avoid: "A seaside resort: anchors, rope borders, navy and red stripes, seagulls on the headings.",
    cues: { goals: ["visit", "order", "book"], angles: ["place", "craft"], materials: ["sol", "morje", "riba", "oljka", "solinar"], local: true },
  },
  {
    id: "pohorje-forest",
    name: "Spruce forest",
    pitch: "A dense Pohorje spruce forest: tall dark-green verticals like trunks, bark brown, a tight column rhythm, light breaking through in one bright band.",
    family: "place",
    slovene: true,
    trades: { fit: ["tourist-farm", "builder", "physio", "restaurant"], never: ["dental", "accountant", "hairdresser"], subOnly: ["carpentry", "roofing"] },
    axes: {
      ground: ["dark", "white"],
      type: ["bitter-karla", "fraunces-source-sans", "archivo-public-sans"],
      palette: ["deep", "earth", "muted"],
      imagery: ["full-bleed", "natural", "monochrome"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "calm",
    },
    signatures: ["imagery/full-bleed", "ornament/trunk-lines", "texture/bark"],
    references: ["markacija", "globina"],
    avoid: "A cabin theme: wood texture as the page ground, pine-tree icons, campfire orange.",
    cues: { goals: ["visit", "book", "enquire"], angles: ["place", "craft"], materials: ["les", "gozd", "smreka", "borovnice", "tesar"], local: true },
  },
  {
    id: "old-town-roofs",
    name: "Old-town roofs",
    pitch: "Red tile roofs seen from a bell tower in Piran: a patchwork of terracotta planes at angles, ochre walls, narrow lanes as the gaps between blocks.",
    family: "place",
    slovene: true,
    trades: { fit: ["restaurant", "builder", "tourist-farm", "bakery", "shop"], never: ["dental", "accountant", "car-repair"], subOnly: ["roofing"] },
    axes: {
      ground: ["white", "tint"],
      type: ["lora-karla", "garamond-karla", "bitter-karla"],
      palette: ["earth", "warm", "deep"],
      imagery: ["offset-block", "full-bleed"],
      shape: ["cut", "square"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["motif/tiles", "mask/cut", "imagery/offset-block", "composition/opener/patchwork"],
    references: ["jedilnik", "cevi"],
    avoid: "Terracotta everywhere, a postcard of the old town on every section, a Mediterranean script font.",
    cues: { goals: ["visit", "book"], angles: ["place", "craft"], materials: ["streha", "opeka", "strešniki", "kamen", "riba"], local: true },
  },
  {
    id: "hop-gardens",
    name: "Hop gardens",
    pitch: "Savinja hop gardens: tall wire trellises in strict rows, green climbing verticals, a pole-and-wire grid drawn lightly over the page.",
    family: "place",
    slovene: true,
    trades: { fit: ["restaurant", "tourist-farm", "shop", "bakery"], never: ["dental", "car-repair", "accountant"], subNever: ["boutique"] },
    axes: {
      ground: ["white"],
      type: ["archivo-public-sans", "bitter-nunito-sans", "space-grotesk-public-sans"],
      palette: ["earth", "cool", "two-colour"],
      imagery: ["full-bleed", "natural"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["motif/wire", "imagery/full-bleed", "ornament/trellis-grid"],
    references: ["markacija", "proge"],
    avoid: "A beer brand: hop cones on every heading, amber and gold, a pub chalkboard.",
    cues: { goals: ["visit", "order"], angles: ["place", "craft"], materials: ["hmelj", "pivo", "žica", "polje"], local: true },
  },
  {
    id: "meadow-orchard",
    name: "Meadow orchard",
    pitch: "High-stem fruit trees scattered over a meadow: round canopies on a soft green ground, airy uneven spacing, the fruit the only bright colour.",
    family: "place",
    trades: { fit: ["tourist-farm", "bakery", "shop", "restaurant"], never: ["car-repair", "dental", "accountant", "physio", "builder"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-nunito-sans", "lora-dm-sans", "bitter-nunito-sans"],
      palette: ["earth", "bright", "muted"],
      imagery: ["rounded", "natural"],
      shape: ["soft", "arch"],
      density: ["airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["mask/circle", "imagery/rounded", "ornament/canopy-shape"],
    references: ["markacija", "skorja"],
    avoid: "Apple clip art, a red-and-green Christmas palette, round photos lined up in a rigid row.",
    cues: { goals: ["visit", "order"], angles: ["place", "craft"], materials: ["jabolka", "hruške", "sadje", "sok", "kis", "žganje"], local: true },
  },
  {
    id: "hayrack",
    name: "Hayrack bays",
    pitch: "The Slovene double hayrack: a rhythm of upright posts and horizontal slats under one roof line, the content set in the bays between the posts.",
    family: "place",
    slovene: true,
    trades: { fit: ["tourist-farm", "builder", "restaurant", "shop", "bakery"], never: ["dental", "accountant", "physio"], subOnly: ["carpentry", "roofing"], subNever: ["boutique"] },
    axes: {
      ground: ["white", "tint"],
      type: ["bitter-karla", "archivo-archivo", "fraunces-source-sans"],
      palette: ["earth", "deep", "two-colour"],
      imagery: ["framed", "natural"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["motif/joint", "ornament/hayrack-bays", "composition/services/bays"],
    references: ["markacija", "cevi"],
    avoid: "A rustic theme: wood grain everywhere, a hayrack photo behind every block, a beige page.",
    cues: { goals: ["visit", "enquire"], angles: ["place", "craft", "family-history"], materials: ["les", "seno", "kozolec", "tesar", "streha"], local: true },
  },
  {
    id: "karst-cave",
    name: "Karst cave",
    pitch: "Inside a karst cave: a deep ground, pale limestone forms lit from one side, dripstone verticals, one warm light colour on what matters.",
    family: "place",
    slovene: true,
    trades: { fit: ["restaurant", "tourist-farm", "shop", "hairdresser"], never: ["car-repair", "dental", "accountant", "builder"], subNever: ["florist"] },
    axes: {
      ground: ["dark"],
      type: ["garamond-figtree", "newsreader-libre-franklin", "fraunces-source-sans"],
      palette: ["deep", "warm", "muted"],
      imagery: ["monochrome", "full-bleed", "arched"],
      shape: ["arch"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["mask/arch", "imagery/monochrome", "ornament/dripstone"],
    references: ["globina", "jedilnik"],
    avoid: "A theme-park cave: neon lighting, glowing gradients, stalactites on every edge, a pure black ground.",
    cues: { goals: ["visit", "book"], angles: ["place", "speciality"], materials: ["klet", "kamen", "vino", "sir", "pršut"], local: true },
  },
];

const CONTEMPORARY: readonly Stance[] = [
  {
    id: "editorial-magazine",
    name: "Editorial magazine",
    pitch: "A magazine spread: a big serif headline over a single strong photo, pull quotes in the margin, columns that start and stop.",
    family: "contemporary",
    trades: { fit: ["*"], never: ["car-repair"] },
    axes: {
      ground: ["white", "dark"],
      type: ["newsreader-libre-franklin", "fraunces-source-sans", "garamond-figtree"],
      palette: ["monochrome", "neutral", "deep"],
      imagery: ["full-bleed", "monochrome", "natural"],
      shape: ["square"],
      density: ["airy", "regular"],
      rhythm: ["alternate", "inverse-accents"],
      motion: "calm",
    },
    signatures: ["typeTreatment/drop-cap", "composition/opener/cover-spread", "imagery/full-bleed"],
    references: ["jedilnik", "mirno"],
    avoid: "A blog template: equal cards, tiny captions, italic accent words in a headline no larger than the body.",
    cues: { goals: ["browse", "visit", "book"], angles: ["person", "family-history", "craft"] },
  },
  {
    id: "colour-block",
    name: "Colour block",
    pitch: "Large flat fields of two or three strong colours meet at hard edges; the type sits on them, the photos are cut into them.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "physio", "shop", "car-repair", "restaurant"], never: ["accountant"] },
    axes: {
      ground: ["white", "dark"],
      type: ["bricolage-figtree", "bricolage-public-sans", "space-grotesk-public-sans"],
      palette: ["bright", "signal", "two-colour"],
      imagery: ["duotone", "offset-block", "natural"],
      shape: ["square", "soft"],
      density: ["regular", "compact"],
      rhythm: ["inverse-accents", "alternate"],
      motion: "lively",
    },
    signatures: ["treatment/tint", "imagery/duotone", "composition/opener/split-field"],
    references: ["ogledalo", "lido"],
    avoid: "A children's toy shop: every colour at once, gradients between them, rounded everything, no calm block anywhere.",
    cues: { goals: ["book", "call", "browse"], angles: ["speed", "person", "value"] },
  },
  {
    id: "oversized-type",
    name: "Oversized type",
    pitch: "One word of the business at wall size, cropped by the page edge, everything else set small; the type is the picture.",
    family: "contemporary",
    trades: { fit: ["*"], never: [] },
    axes: {
      ground: ["white", "dark"],
      type: ["inter-tight-inter", "archivo-archivo", "bricolage-figtree"],
      palette: ["monochrome", "signal", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/numeral", "typeTreatment/cropped-word", "composition/opener/wall-word"],
    references: ["crke", "proge", "ogledalo"],
    avoid: "A shouting page: every heading huge, letters cropped until unreadable, small tracked capitals under each.",
    cues: { goals: ["browse", "visit", "book"], angles: ["person", "speciality"] },
  },
  {
    id: "documentary-monochrome",
    name: "Documentary monochrome",
    pitch: "Black-and-white documentary photos of the work and the hands doing it, large and unretouched, one colour kept only for what to press.",
    family: "contemporary",
    trades: { fit: ["car-repair", "builder", "hairdresser", "bakery", "restaurant", "physio", "tourist-farm"], never: [] },
    axes: {
      ground: ["white", "dark"],
      type: ["newsreader-libre-franklin", "inter-tight-inter", "archivo-public-sans"],
      palette: ["monochrome", "neutral", "signal"],
      imagery: ["monochrome", "full-bleed"],
      shape: ["square"],
      density: ["regular", "airy"],
      rhythm: ["alternate"],
      motion: "still",
    },
    signatures: ["imagery/monochrome", "treatment/grain", "composition/opener/photo-essay"],
    references: ["globina", "mirno"],
    avoid: "A gloomy portfolio: grey on grey, a pure black ground with pure white text, photos too small to see the work.",
    cues: { goals: ["call", "visit", "book"], angles: ["craft", "person"] },
  },
  {
    id: "brutalist-minimal",
    name: "Brutalist minimal",
    pitch: "Raw structure on show: visible grid lines, hairline rules, big flush-left type, one hard colour, no decoration and no softening.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "shop", "accountant", "builder", "physio", "car-repair"], never: ["bakery", "tourist-farm"], subNever: ["deli", "florist"] },
    axes: {
      ground: ["white"],
      type: ["space-grotesk-plex", "inter-tight-inter", "archivo-public-sans"],
      palette: ["monochrome", "signal", "two-colour"],
      imagery: ["natural", "monochrome"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["shape/square", "texture/visible-grid", "divider/hairline", "typeTreatment/flush-left-display"],
    references: ["proge", "racun"],
    avoid: "Broken on purpose: overlaps nobody can read, default blue links, tiny text, monospace labels.",
    cues: { goals: ["enquire", "book", "browse"], angles: ["speciality", "person"] },
  },
  {
    id: "photocopied-zine",
    name: "Photocopied zine",
    pitch: "A photocopied zine: high-contrast photos, cut-out headlines glued slightly off square, one colour overprinted, pages that look made by hand.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "shop", "restaurant", "bakery"], never: ["dental", "accountant", "physio"] },
    axes: {
      ground: ["white"],
      type: ["bricolage-figtree", "archivo-archivo", "space-grotesk-public-sans"],
      palette: ["monochrome", "bright", "two-colour"],
      imagery: ["monochrome", "duotone", "offset-block"],
      shape: ["cut", "square"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "lively",
    },
    signatures: ["treatment/grain", "imagery/offset-block", "typeTreatment/cut-out-headline"],
    references: ["crke", "ogledalo"],
    avoid: "Grunge pastiche: noise on every surface, torn paper on every edge, ransom-note letters.",
    cues: { goals: ["visit", "browse"], angles: ["person", "craft"] },
  },
  {
    id: "gallery-wall",
    name: "Gallery wall",
    pitch: "A white gallery wall: a few pictures hung with big gaps between them, a small precise caption beside each, nothing competing with the work.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "shop", "dental", "physio", "restaurant", "builder"], never: [] },
    axes: {
      ground: ["white"],
      type: ["garamond-figtree", "inter-tight-dm-sans", "newsreader-libre-franklin"],
      palette: ["neutral", "monochrome", "muted"],
      imagery: ["framed", "natural"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["imagery/framed", "typeTreatment/side-caption", "composition/gallery/hung-wall"],
    references: ["mirno", "ogledalo"],
    avoid: "An empty page: tiny photos lost in space, captions in grey too pale to read, one centred column.",
    cues: { goals: ["browse", "book"], angles: ["craft", "speciality"] },
  },
  {
    id: "risograph",
    name: "Risograph",
    pitch: "Risograph print: two bright inks, fluorescent pink and teal or red and blue, overprinting in flat grainy fills, the photos as two-ink duotones.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "shop", "bakery", "restaurant", "physio"], never: ["dental", "accountant"] },
    axes: {
      ground: ["white"],
      type: ["bricolage-public-sans", "space-grotesk-public-sans", "archivo-archivo"],
      palette: ["bright", "two-colour"],
      imagery: ["duotone", "offset-block"],
      shape: ["square", "soft"],
      density: ["regular"],
      rhythm: ["alternate"],
      motion: "lively",
    },
    signatures: ["treatment/duotone", "treatment/grain", "imagery/duotone"],
    references: ["lido", "val"],
    avoid: "Every colour fluorescent at once, grain over the text, misregistration that makes words hard to read.",
    cues: { goals: ["visit", "book", "browse"], angles: ["person", "value"] },
  },
  {
    id: "split-screen",
    name: "Split screen",
    pitch: "The page split down the middle: one half a held colour or photo, the other half the words, the split kept from the first screen to the footer.",
    family: "contemporary",
    trades: { fit: ["*"], never: [] },
    axes: {
      ground: ["white", "dark"],
      type: ["inter-tight-dm-sans", "newsreader-libre-franklin", "manrope-public-sans"],
      palette: ["two-colour", "deep", "neutral"],
      imagery: ["full-bleed", "natural"],
      shape: ["square"],
      density: ["regular"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["imagery/full-bleed", "composition/opener/split-field", "motion/pinned-half"],
    references: ["nasmeh", "mirno"],
    avoid: "Two halves that don't relate, a split that falls apart on phones, centred text on both sides.",
    cues: { goals: ["book", "call", "enquire"], angles: ["person", "speciality"] },
  },
  {
    id: "moving-type",
    name: "Moving type",
    pitch: "Type that moves a little: one slow line of the client's own short phrases crossing the page, headings that settle into place as they scroll in.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "shop", "restaurant", "bakery", "physio"], never: ["accountant", "dental"] },
    axes: {
      ground: ["white", "dark"],
      type: ["bricolage-figtree", "inter-tight-inter", "archivo-archivo"],
      palette: ["bright", "signal", "monochrome"],
      imagery: ["natural", "full-bleed"],
      shape: ["square", "soft"],
      density: ["regular"],
      rhythm: ["inverse-accents"],
      motion: "lively",
    },
    signatures: ["font/bricolage-figtree", "motion/marquee", "typeTreatment/marquee-line"],
    references: ["gladina", "crke"],
    avoid: "A slot machine: everything animated, text unreadable while it moves, motion that ignores reduced-motion settings.",
    cues: { goals: ["visit", "book", "browse"], angles: ["person", "speed"] },
  },
  {
    id: "still-life",
    name: "Still life",
    pitch: "One object per section photographed on a flat colour that matches it, hard light, one short caption: the page as a set of still lifes.",
    family: "contemporary",
    trades: { fit: ["bakery", "shop", "restaurant", "hairdresser", "tourist-farm"], never: ["accountant"] },
    axes: {
      ground: ["tint", "white"],
      type: ["fraunces-source-sans", "inter-tight-dm-sans", "lora-dm-sans"],
      palette: ["bright", "warm", "muted"],
      imagery: ["natural", "offset-block"],
      shape: ["square"],
      density: ["airy"],
      rhythm: ["inverse-accents"],
      motion: "still",
    },
    signatures: ["imagery/natural", "treatment/tint", "composition/opener/object-on-colour"],
    references: ["deska", "skorja"],
    avoid: "Stock flat lays: coffee cups and laptops, props the client doesn't sell, catalogue drop shadows.",
    cues: { goals: ["order", "browse", "visit"], angles: ["craft", "speciality"] },
  },
  {
    id: "portrait-first",
    name: "Portrait first",
    pitch: "The owner's portrait carries the page: one large honest photo of the person, their own words beside it, their name set plainly underneath.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "physio", "dental", "accountant", "builder", "car-repair", "tourist-farm"], never: [] },
    axes: {
      ground: ["white", "tint"],
      type: ["newsreader-libre-franklin", "garamond-figtree", "inter-tight-dm-sans"],
      palette: ["muted", "warm", "neutral"],
      imagery: ["natural", "framed", "monochrome"],
      shape: ["square", "arch"],
      density: ["airy"],
      rhythm: ["alternate"],
      motion: "calm",
    },
    signatures: ["imagery/natural", "mask/arch", "composition/opener/portrait"],
    references: ["pregib", "mirno"],
    avoid: "A corporate headshot: grey backdrop, crossed arms, a quote the person never said.",
    cues: { goals: ["book", "call", "enquire"], angles: ["person"] },
  },
  {
    id: "line-drawing",
    name: "Continuous line",
    pitch: "Everything drawn in one continuous line: the trade's objects, the street, a portrait, in the accent colour on white, photos used sparingly.",
    family: "contemporary",
    trades: { fit: ["*"], never: [] },
    axes: {
      ground: ["white"],
      type: ["fraunces-nunito-sans", "figtree-figtree", "lora-dm-sans"],
      palette: ["two-colour", "warm", "cool"],
      imagery: ["natural", "rounded"],
      shape: ["soft"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["motif/bend", "ornament/continuous-line", "composition/opener/drawn-object"],
    references: ["pregib", "val"],
    avoid: "Clip-art doodles: a drawing on every block, scribbled arrows, sketchy fonts.",
    cues: { goals: ["book", "enquire", "visit"], angles: ["person", "craft"] },
  },
  {
    id: "night-ground",
    name: "Night ground",
    pitch: "A dark page like a lit window at night: a deep ground, warm light on the photos, light off-white type, one warm accent for the way in.",
    family: "contemporary",
    trades: { fit: ["restaurant", "hairdresser", "bakery", "tourist-farm", "shop"], never: [] },
    axes: {
      ground: ["dark"],
      type: ["garamond-figtree", "fraunces-source-sans", "newsreader-libre-franklin"],
      palette: ["deep", "warm"],
      imagery: ["full-bleed", "natural"],
      shape: ["square", "arch"],
      density: ["airy"],
      rhythm: ["flat"],
      motion: "calm",
    },
    signatures: ["imagery/full-bleed", "treatment/tint", "composition/opener/lit-window"],
    references: ["jedilnik", "globina", "skorja"],
    avoid: "A nightclub: pure black, neon glows, gradient text, gold on everything.",
    cues: { goals: ["visit", "book"], angles: ["place", "speciality"] },
  },
];

export const STANCES: readonly Stance[] = [...PRINT, ...SIGNAGE, ...CRAFT, ...MODERNIST, ...PLACE, ...CONTEMPORARY];
