/**
 * The starter stance deck (design-studio.md §5.2): enough to deal and test with. The full deck of 80 comes with the
 * inventory (I8). Four are rooted in Slovene visual culture (trail marker, beehive panel, Plečnik-era classicism, karst
 * stone). Visual only: no pitch implies a fact, a year or a heritage the client didn't give.
 */
import type { Stance } from "./deck.ts";

export const STANCES: readonly Stance[] = [
  {
    id: "workshop-docket",
    name: "Workshop docket",
    pitch: "The page reads like the job ticket you get with your car: carbon-copy blue, stamped numbers, typed lines.",
    family: "print",
    trades: { fit: ["car-repair", "builder", "shop"], never: ["dental", "hairdresser", "physio"] },
    axes: {
      ground: ["white", "tint"],
      type: ["space-grotesk-plex", "ibm-plex-sans", "archivo-public-sans"],
      palette: ["cool", "signal", "two-colour"],
      imagery: ["natural", "framed"],
      shape: ["square", "cut"],
      density: ["compact", "regular"],
      motion: "still",
    },
    signatures: ["fact/ticket", "fact/stamp", "mask/ticket", "typeTreatment/typed-line"],
    references: ["tablica", "racun"],
    avoid: "A form: grey boxes, every line ruled, nothing large enough to read from across the street.",
    cues: { goals: ["call", "enquire"], angles: ["speed", "value"], materials: ["olje", "guma", "orodje", "cev"] },
  },
  {
    id: "seed-packet",
    name: "Seed packet",
    pitch: "A paper packet you buy at the market: one drawn object on a flat colour, the name in a curved label, small print on the back.",
    family: "print",
    trades: { fit: ["bakery", "shop", "tourist-farm"], never: ["car-repair", "accountant", "dental"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-nunito-sans", "bitter-karla", "lora-karla"],
      palette: ["earth", "warm", "muted"],
      imagery: ["natural", "rounded", "duotone"],
      shape: ["soft", "arch"],
      density: ["regular", "airy"],
      motion: "calm",
    },
    signatures: ["fact/tag", "mask/arch", "treatment/duotone", "ornament/drawn-object"],
    references: ["etiketa", "skorja"],
    avoid: "A farmhouse cliché: kraft brown everywhere, script fonts and wheat ears on every heading.",
    cues: { goals: ["visit", "order", "browse"], angles: ["craft", "speciality"], materials: ["seme", "moka", "med", "zelenjava", "sadje", "rože"] },
  },
  {
    id: "trail-marker",
    name: "Trail marker",
    pitch: "The red-and-white trail blaze painted on rock: bold dots of colour guide the eye down the page, signs point the way.",
    family: "signage",
    trades: { fit: ["tourist-farm", "physio", "shop", "restaurant"], never: ["accountant", "dental"] },
    axes: {
      ground: ["white", "tint"],
      type: ["archivo-archivo", "bitter-nunito-sans", "space-grotesk-public-sans"],
      palette: ["signal", "two-colour", "earth"],
      imagery: ["full-bleed", "natural"],
      shape: ["square", "cut"],
      density: ["regular", "airy"],
      motion: "calm",
    },
    signatures: ["motif/trail", "fact/tag", "ornament/trail-blaze", "divider/ridge-line"],
    references: ["markacija"],
    avoid: "A hiking-club poster: arrows everywhere, a mountain silhouette behind every section.",
    cues: { goals: ["visit", "book"], angles: ["place"], materials: ["pot", "gora", "planina", "gozd", "kamen"], local: true },
  },
  {
    id: "beehive-panel",
    name: "Beehive panel",
    pitch: "The painted fronts of Slovene beehives: a small scene in a framed panel, saturated folk colours on a plain ground, panels side by side.",
    family: "craft",
    trades: { fit: ["bakery", "tourist-farm", "shop", "restaurant"], never: ["car-repair", "dental", "accountant", "physio"] },
    axes: {
      ground: ["white", "tint"],
      type: ["fraunces-source-sans", "bitter-karla", "garamond-karla"],
      palette: ["bright", "warm", "earth"],
      imagery: ["framed", "rounded"],
      shape: ["soft", "arch"],
      density: ["regular"],
      motion: "still",
    },
    signatures: ["ornament/beehive-panel", "mask/arch", "imagery/framed", "fact/seal"],
    references: ["etiketa", "skorja"],
    avoid: "A souvenir shop: painted panels on every block, no air, every colour at full strength at once.",
    cues: { goals: ["visit", "order"], angles: ["family-history", "craft", "place"], materials: ["med", "les", "kruh", "potica", "vosek"], local: true },
  },
  {
    id: "plecnik-classicism",
    name: "Plečnik-era classicism",
    pitch: "Ljubljana's columns and stone lettering: a calm classical grid, carved capitals, one column of colour, generous margins.",
    family: "modernist",
    trades: { fit: ["accountant", "dental", "restaurant", "shop", "physio"], never: ["car-repair"] },
    axes: {
      ground: ["white", "tint"],
      type: ["garamond-figtree", "newsreader-libre-franklin", "garamond-karla"],
      palette: ["deep", "muted", "neutral"],
      imagery: ["arched", "framed", "monochrome"],
      shape: ["square", "arch"],
      density: ["airy", "regular"],
      rhythm: ["flat", "alternate"],
      motion: "still",
    },
    signatures: ["mask/arch", "typeTreatment/carved-capitals", "divider/double-rule", "imagery/arched"],
    references: ["racun", "jedilnik"],
    avoid: "A bank or a funeral home: grey marble, every heading centred, nothing that says what the business does.",
    cues: { goals: ["book", "enquire", "visit"], angles: ["person", "speciality"], materials: ["kamen", "marmor"], local: true },
  },
  {
    id: "swiss-grid",
    name: "Swiss grid",
    pitch: "A strict modular grid, one grotesk in a few sizes, flush-left text and numbers set large, colour used only to point.",
    family: "modernist",
    trades: { fit: ["*"], never: ["bakery", "tourist-farm"] },
    axes: {
      ground: ["white"],
      type: ["inter-tight-inter", "inter-tight-dm-sans", "ibm-plex-sans"],
      palette: ["neutral", "signal", "monochrome"],
      imagery: ["natural", "monochrome", "full-bleed"],
      shape: ["square"],
      density: ["compact", "regular"],
      rhythm: ["flat"],
      motion: "still",
    },
    signatures: ["fact/numeral", "typeTreatment/giant-numeral", "composition/opener/grid-poster"],
    references: ["racun", "proge"],
    avoid: "A software landing page: three feature cards, centred hero, a gradient button.",
    cues: { goals: ["call", "book", "enquire"], angles: ["speed", "value", "speciality"] },
  },
  {
    id: "karst-stone",
    name: "Karst stone",
    pitch: "Dry-stone walls and red soil of the Karst: a pale stone ground, deep red and olive, heavy blocks set like masonry.",
    family: "place",
    trades: { fit: ["restaurant", "tourist-farm", "shop", "builder"], never: ["dental", "car-repair", "hairdresser"] },
    axes: {
      ground: ["tint", "white"],
      type: ["bitter-karla", "fraunces-source-sans", "newsreader-libre-franklin"],
      palette: ["earth", "deep", "muted"],
      imagery: ["natural", "full-bleed", "offset-block"],
      shape: ["square", "cut"],
      density: ["regular", "airy"],
      motion: "still",
    },
    signatures: ["texture/stone", "imagery/offset-block", "divider/stone-course", "mask/cut"],
    references: ["etiketa", "jedilnik"],
    avoid: "A wine-bar cliché: dark wood, gold script, a grape vine on every heading.",
    cues: { goals: ["visit", "book", "order"], angles: ["place", "craft", "family-history"], materials: ["kamen", "teran", "pršut", "vino", "sol", "oljka"], local: true },
  },
  {
    id: "editorial-magazine",
    name: "Editorial magazine",
    pitch: "A magazine spread: a big serif headline over a single strong photo, pull quotes in the margin, columns that start and stop.",
    family: "contemporary",
    trades: { fit: ["*"], never: ["car-repair"] },
    axes: {
      ground: ["white", "dark"],
      type: ["newsreader-libre-franklin", "fraunces-source-sans", "garamond-figtree"],
      palette: ["monochrome", "neutral", "deep"],
      imagery: ["full-bleed", "monochrome", "natural"],
      shape: ["square"],
      density: ["airy", "regular"],
      rhythm: ["alternate", "inverse-accents"],
      motion: "calm",
    },
    signatures: ["typeTreatment/drop-cap", "composition/opener/cover-spread", "imagery/full-bleed"],
    references: ["jedilnik", "mirno"],
    avoid: "A blog template: a grid of equal cards, tiny captions, a headline no larger than the body.",
    cues: { goals: ["browse", "visit", "book"], angles: ["person", "family-history", "craft"] },
  },
  {
    id: "colour-block",
    name: "Colour block",
    pitch: "Large flat fields of two or three strong colours meet at hard edges; the type sits on them, the photos are cut into them.",
    family: "contemporary",
    trades: { fit: ["hairdresser", "physio", "shop", "car-repair", "restaurant"], never: ["accountant"] },
    axes: {
      ground: ["white", "dark"],
      type: ["bricolage-figtree", "bricolage-public-sans", "space-grotesk-public-sans"],
      palette: ["bright", "signal", "two-colour"],
      imagery: ["duotone", "offset-block", "natural"],
      shape: ["square", "soft"],
      density: ["regular", "compact"],
      rhythm: ["inverse-accents", "alternate"],
      motion: "lively",
    },
    signatures: ["treatment/tint", "imagery/duotone", "composition/opener/split-field"],
    references: ["ogledalo", "lido"],
    avoid: "A children's toy shop: every colour at once, rounded everything, no calm block anywhere.",
    cues: { goals: ["book", "call", "browse"], angles: ["speed", "person", "value"] },
  },
];
